### ISSUE TITLE
scene code 기법의 오류 & 해결법

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#1]
영어판에는 `prt-scene-comment` 클래스에 적용된 스타일이 없어서 
`var sceneCode = document.querySelectorAll("[class^='prt-scene-comment']")[0].style.cssText.split(',')[1].trim();`
이 부분은 영어판으로할때는 에러 뿜음 ㅠㅠ..

그래서 영어판과 일어판에 모두 적용 가능하며 이벤트 페이지와 아카이브의 지난 이벤트 페이지에서도 모두 적용 가능한 공통점으로 도대체 뭐가 있을까 삽질을 해봤더니 찾았음. 적어도 이벤트에 대해서는 찾았음.

각각의 사이드 스토리에서 오프닝 페이지는 항상 `scene_evt200515_cp0_q1_s10 `이라는 scene 값이 URL 맨 끝에있음. 맨 끝에 없더라도 scene_evt200515_cp0_q1_s10/top/ 이런식으로 맨 끝 즈음에 있음. 그리고, 오프닝 이후의 에피소드들은 `http://game.granbluefantasy.jp/#quest/cleared_scene/scene_evt200515_cp1_q1_s10/754811`
이런 URL인데 맨 끝에 보면 숫자가있음. 여기서 75481까지가 ID고 뒤에 붙는 1은 에피소드1의 첫번째 이야기를 뜻함. 

메인 스토리에 대한 공통점 찾기는 힘들어서 좀 더 찾아보고 현재 이슈를 해결해보겠음.

내가 실력없고, 군인이라 시간이 극히 적어서 스토리 번역 진척 속도에 민폐끼치는것같은데 ㅈㅅㅈㅅ. 요번주 수요일이랑 토요일에는 근무라 컴터 못하기도하고.

**Comment by sidewinderk** [comment]
걱정안해도됨.
어느시점이든 번역이 완료된 텍스트를 다른 포멧으로 바꾸는건 어렵지 않음.

해결법에 대해선..
영문판 텍스트도 가져오려면 비슷하게 퀘스트 코드를 불러오는 파트가 있을 거라고 생각함.
궁극적으로는 그 쪽을 찾아서 현재 적용된 방법과 같게 적용하면될듯.
혹은, 영문판만 다르게 작동하도록 수정을 하는 방법이 쉬울 수도 있음.

**Comment by ajh1000** [comment]
영문판에 대한 해결법이 생각남. 오늘은 근무라 못하고 내일 오후에 조치해볼 예정. 

1. journal 페이지 밑에 메인스토리 페이지를 누르자마자 나오는 이미지 태그들의 src를 읽기.
2. 순서대로 읽어들인 src의 id번호(20001,20002....)에 대응하는 scene_cpXX_qXX 값을 순서대로 적용해주기. 
3. 이후 추출작업을 위해 스토리 한 개 진행 후 getText 실행하면  scene code값에 "20001,scene_cpXX_qXX" 이런 식으로 적용해서 넣어주기. 아무튼 이런 비슷한 방법으로 시도해볼예정.

**Comment by ajh1000** [comment]
[최근 커밋](https://github.com/ajh1000/gbfTransKor/commit/159360018943aaa2949c2e29b4c558a180282e8b)

스토리 번역 적용되는 것 확인. 이벤트는 한 가지만 더 구현하면 완성. 

데이터 양식 변경. 
index, sceneCode, orig, kr
0,"scene_cp4_q4,1",~~~,~~~~

오늘 10시 40분 즈음에 다시 컴터 키고 이벤트 구현 마저 완료 하겠음. 내일은 다듬고, 설명 문서 작성해서 이슈 마무리하겠음.

**Comment by sidewinderk** [comment]
체크하고있음. 오늘자 작업 완료되면 한번 적용해봄.

**Comment by ajh1000** [comment]
아직 메인스토리만 적용됨. 이벤트 적용은 완료되면 바로 이슈달겟슴

**Comment by ajh1000** [comment]
다 했음. 이제 여기서.. 어떤거 테스트하면 될려나. 

이벤트 플레이 페이지에서 스토리 진행했을때 번역 적용 확인.
journal(예전 이야기 보는 페이지) 에서 이벤트 번역 적용 확인.

메인 스토리 플레이 페이지에서 스토리 진행했을때 번역 적용 확인.
journal(예전 이야기 보는 페이지) 에서 메인스토리 번역 적용 확인.

이외에 테스트할 부분이 어떤게 있으면 될거같음?

**Comment by sidewinderk** [comment]
확인했음.
큰 틀에서 변화해야하는 점이, 모든 CSV head의 jp 파트가 orig 로 바뀌어야하는듯.
이건 구글독스 단에서 해결 할 수 있는 문제이니 적용하고 일괄 수정하겠음.

그럼 수정된 파트 (contents.js/popup.js) 포함해서 pull-request해주면 적용하겠음.

**Comment by ajh1000** [comment]
땡큐함니다 그런데 잠시만... 초기에 있었던 문제좀 해결하고 풀리퀘스트하겠음. 
계정 생성하고 스토리 시작하는 사람들은 빠른 텍스트 기능이 안켜져있어서 텍스트가 순서대로 나오는데, 이건 저번에 님이 말했던것처럼 빠른 텍스트 기능이 켜져있어야 스토리 텍스트가 한번에 땃 하고 나옴. 

기능 꺼져있는 사람들 대상으로 번역 기능이 동작하도록 만들어줘야하는데 이게 힘드네. 

좀더해보고 어려우면 도움요청하겠음

**Comment by sidewinderk** [comment]
텍스트가 한글자씩 나오는 문제는 본질적인 해결이 쉽지않을 것 같음.
타협안으로써, 옵션에서 텍스트 한번에 표시 기능을 켤 수 있는 단계까지(튜토리얼 마무리)의 퀘스트는 다 한글자씩 나오는 걸 기반으로 번역을 진행해둬야하지 않을까 싶음.

**Comment by ajh1000** [comment]
님 말이 맞음. 타협안을 생각하는것도 좋겠음. 그전에 먼저 시도해볼건 한글자씩 나오는 중에는 ico-cursor-talk 클래스의 display 속성이 none;이고, 전체 글자가 나왔을 때는 ico-cursor-talk 클래스의display 속성이 block;이 됨. 그래서 dispaly 속성이 block이 됐을때 GetTranslatedStoryText 함수를 호출하고싶은데 이런 코드를 어디다가 짜야할지 모르겠음 ㅋㅋ 일단 계속 시도중

**Comment by sidewinderk** [comment]
그렇다면, MutationObserver로 땡겨온 DOM의 property를 확인함으로서 Go/Stop을 결정해주면 될 것 같음.
(텍스트가 흐르는 동안에는 해당 DOM이 계속 바뀌는 중이므로 MutationObserver가 정상적으로 감시를 하고 있을 것.)

쉽게 생각하면.. 
ObserveSceneText() 함수에서 감시하는 DOM을 prt-log-display 로 하지 않고, ico-cursor-talk 로 한 다음, 아래 if 문에서 oText.style.display 가 block 일 때 까지 기다렸다가(!oText 처럼.), prt-log-display를 sceneObserver에 넣어주는 방식으로 해결할 수 있을듯.

다만 이렇게 하더라도 한글자씩 나오는 과정은 생략할 수 없음.

**Comment by ajh1000** [comment]
오.. 해보겠슴

**Comment by ajh1000** [comment]
ㅇㅋ 해결함. 계정 처음만들고 시작하는 튜토리얼에서도 정상 확인. 완벽히 동작하는건아니지만(장면이 전환될때 텍스트가 살짝 깜빡거림) 이 정도는 타협안으로서 적절한듯함. 

앞으로 추가로 구현해야만 하는 기능들 생각나서 적어봄. 

1. 선택지가 떴을때, 각 선택지에 해당하는 텍스트들을 추출해야함.
1-1. 선택지를 눌렀을때 나오는 텍스트들은 어떤 식으로 추출해야하는지 생각하기.

2. 최근 이벤트 한것들중에 The Art Of Merct 이벤트가있는데 여기서 엔딩 볼때 샤렘 캐릭을 가지고있으면 특별한 텍스트를 추가로 볼수있음. 이런 분기문들은 어떻게 추출할건지.

**Comment by sidewinderk** [comment]
흠.. 선택지와 마찬가지로, 특정캐릭터가 있는지 여부에 대한 텍스트의 옵션을 url 칸에 넣고 설정을 해줘야겠는데, 일단 도감에서 캐릭터 에피소드를 볼 때 특정 캐릭터가 있는지 여부를 물어보는 퀘스트가 있음. 그걸 기준으로 주소나 퀘스트 코드가 어떻게 바뀌는지를 살펴봐야할듯.

**Comment by ajh1000** [comment]
chrome.devtools.network API를 활용하여 scene code값을 정확하게 얻어옴. 이 이슈는 이제 개발이 완료됐으므로 닫겠음.
