### ISSUE TITLE
저작권?

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#12]
샤니마스 한패를 보면 깃허브 소스랑 번역 데이터에 라이센스 걸었는데 우리도 롱런을 위해서 그렇게 해야되나 싶음. 

[샤니마스 한패 개발자의 '한패 라이센스에 관한 개인적 의견'](https://gall.dcinside.com/mgallery/board/view/?id=shinycolors&no=195031&_rk=Zxh&s_type=search_name&s_keyword=%EB%89%B4%EB%B9%84&page=1)
[샤니마스 한패 개발자의 '한패 라이센스(저작권)에 관하여'](https://gall.dcinside.com/mgallery/board/view/?id=shinycolors&no=195030&_rk=OmR&s_type=search_name&s_keyword=%EB%89%B4%EB%B9%84&page=1)

**Comment by sidewinderk** [comment]
먼저, 번역물에 대해선 따로 고지하지 않았지만 위키피디아 등과 같이 CC BY-NC-SA 이 적용되는게 당연한거 같음.

문제는.. 우리가 뭐 단체도 아니고 해서 이걸 지키지 않은 누군가가 나타났을때(예를들어 소스코드 복붙 해서 쓰고, 본인 광고를 다는 등) 제제할 방법이 있는가? 하면 음.. 없지 않을까..?
실효성이 없을 것 같지만.. 그래도 외양간 미리 손봐둬서 나쁠 건 없을 듯하므로, README 및 시트에 붙여둬야겠음. 

좋은 의견 감사.

**Comment by sidewinderk** [comment]
- Git Repository에 MIT 라이센스 추가함.
- contents.js 및 gbfTrans.js,  gbfTrans_test.js에 샤니마스 중국어 패치 원본에서 가져온 부분에 license 표기
- 시트 메인페이지 하단에 라이센스 관련 라인 추가.
