### ISSUE TITLE
이미지 치환 지연

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#14]
이미지 치환 옵션 적용시 페이지 로드이후 바로 이미지가 치환되지 않고 마우스 커서를 가져가거나 터치를 해줘야 전환되는 경우가 있음.

예시로, 전투 UI에서 하단의 서브 메뉴들(구원요청,참전자,로그 메뉴)이 두드러짐.

번역물 이용시에 치명적인 부분은 아니지만, 고쳐둬야할 부분으로 메모해둠.

**Comment by ajh1000** [comment]
음 전투 화면에서 구원요청 참전자, 로그메뉴 버튼에 마우스 갖다대거나 클릭해도 치환이 안되는데 무슨 문제가있는거지

한번 디버깅해보고 해보겠음.

**Comment by ajh1000** [comment]
![크롬디버깅](https://imgur.com/zrNnb1Z.png)

여기에 브레이크포인트 두고 전투화면에서 새로고침 해봤는데 저길 거쳐가질않음. 
내 생각엔  저런 이미지들은 변화하는 값들이 아니다보니까 mutation 이 일어나질 않는것같음.

**Comment by ajh1000** [comment]
![캡처](https://imgur.com/jM2KLBn.png)

전투화면에서 참전자 버튼에 마우스 갖다댔을때의 상황을 디버깅해보니 저쪽에서 png 파일이기때문에 return이 실행되는것으로 보임.

**Comment by ajh1000** [comment]
![캡처](https://imgur.com/yIHmo1P.png)
GetTranslatedImageDIV 함수에 있는 저 if문에서 3줄을 추가하니까 이제 마우스 갖다댔을때 이미지 치환이 수행됨. 이제 여기서 마우스 갖다대지않고도 전투화면 로딩되자마자 이미지 로드되게끔 바꿔보도록 삽질해봅시다

**Comment by sidewinderk** [comment]
아.. 이 부분은 내가 새 PR 받을 때 자세히 확인안하고 받았다가 덮어씌워진거같네,
꼭꼭 PR하기 직전에 git pull을 한뒤에 보내야 함.

해당부분은
https://github.com/sidewinderk/gbfTransKor/commit/db3a6f27f848e8008518fc5c772c731379d7861c#diff-a482ea1142029551c5e18434b60ea27aL1766

위의 링크에서 볼 수 있듯이, 버튼 하나하나를 모두 예외처리하는건 코드가 너무 복잡해질것 같아서 `window.getComputedStyle` 의 결과에 png 파일이 있으면 자동으로 통과하도록 해뒀었음.

**Comment by sidewinderk** [comment]
https://github.com/sidewinderk/gbfTransKor/commit/eccf18716737bebdb53ae1fa4721270f5593af9d

위 PR로 일단 되살려둠.

**Comment by ajh1000** [comment]
홀리쉿.. 지금 바로 내가 작업했던것들 stash 해버리고 git pull upstream master 수행함. ㅇㅋ 이제 안전.

**Comment by ajh1000** [comment]
1. ObserverBattle 함수에서 요부분 주석으로 감쌈.
![캡처1](https://imgur.com/SqYte88.png)

2. BattleImageObserver 에서 두 줄 추가함.
![캡처2](https://imgur.com/IB5Hjbi.png)


음.. 아무리 디버깅해봐도 전투화면에서 새로고침할때 prt-multi-buttons 클래스는 mutation이 안일어남. 그래서 그냥 prt-sub-command 클래스(CA 자동 버튼, CA 컷신 스킵 버튼)가 이미지 번역될때 같이 번역되게 만들어놓음.

mutation 이 안일어나는 이런 버튼들은 이런식으로 하는것도 좋아보임. 어떻게생각함?

**Comment by sidewinderk** [comment]
그 방법도 고려는 해봤는데, 이 문제가 여기서만 나타는게 아니고, 아카룸 메인 로고라던가 루리아노트 메인 로고 등에서도 종종 발생함.
고로 좀 더 근본적인 해결법을 찾아보는게 좋을 것 같음.

**Comment by ajh1000** [comment]
알겠음. 지금은 임시방편으로서 적용하고 나중에 해결법을 같이 찾아보는게 좋을것같다고 생각함.

**Comment by ajh1000** [comment]
https://github.com/ajh1000/gbfTransKor/commit/5da64825e115d8def5a0c5cc6a8b6cc99970dbd2#diff-a482ea1142029551c5e18434b60ea27aR2507

최근 개발 중에 이 문제가 간단하게 해결해서 댓글담

[기존 코드]
``` var battleInfo_btn = document.querySelectorAll('[class^="prt-sub-command"]');```
[수정 코드]
```var battleInfo_btn = document.querySelectorAll('[class^="prt-command"]');```

전투 화면 중에 회복 버튼 쪽에 있던 버튼들은 이제 바로 번역 됨.

이런 식으로 mutation을 잘 감지할 수 있도록 부모 div를 잡아줘보니 해결됨.

**Comment by ajh1000** [comment]
내가 내일 24시간 근무라 월요일 오후 6시 이후에 PR하겠음. 

mutationobserver가 작동을 안하는 문제 때문에 머리아팠는데 한 단계 상위의 div로 잡아주니까 해결됨. 

퍼포먼스 히트는 별로 없는것같음. 다시 해봐야알겠지만 암튼.

개발이 거의 완료됐으니까 월요일에 다시 찾아오겠음..

**Comment by sidewinderk** [comment]
오케이, 수고하셨슴.

**Comment by ajh1000** [comment]
전투 화면 이미지 번역 지연 이슈 해결 #46

PR 로 이 문제는 해결되보이는데 닫아도 되지않을까함

**Comment by sidewinderk** [comment]
동의함.
