### ISSUE TITLE
일부 번역문 중복 적용

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#15]
css 에서 `content` 속성으로 값이 주어지는 텍스트(예: 메뉴탭이나 버튼 등)를 번역할 때 번역문이 중복 적용되는 경우가 있음.

현재는 `GetTranslatedText` 함수에서 `getComputedStyle(node, ':after')` 을 통해 얻어진 텍스트가 있으면, `className-translated` 라는 이름의 새 css를 추가하여 content 값을 번역문으로 덮어씌워주는 방식을 사용하고 있음.

특정 메뉴 탭이나 버튼 등에서 이 부분이 중복 적용되는 것은 `if (!node.className.includes('-translated'))`을 통과한 것으로 보이므로, `className` 및 `className-translated` 를 적용하는데 있어서 에러가 있을 것으로 생각됨.

번역문 적용에 있어서 제대로 텍스트가 표시되지 않는 문제이므로 가능한 빨리 고쳐야함.

**Comment by ajh1000** [comment]
![크롬디버깅](https://imgur.com/zrNnb1Z.png)

여기에 브레이크포인트 두고 전투화면에서 새로고침 해봤는데 저길 거쳐가질않음. 
내 생각엔  저런 이미지들은 변화하는 값들이 아니다보니까 mutation 이 일어나질 않는것같음.

**Comment by ajh1000** [comment]
이 버그가 발생하는 페이지를 혹시 알려줄수있음? 여러 페이지 돌아다녀봤을땐 문제되보이는게 없어보여서.

**Comment by sidewinderk** [comment]
이 문제는 무기나 소환석 등을 골라서 상한해방 메뉴로 간뒤에, 적절한 재료를 고르고 상한해방을 결정하는 메뉴에서 '상한해방하기' 탭의 글자가 두번 표시되는 문제로 확인할 수 있음.

내 생각엔 새로 추가한 -translated css의 content와, div html 내부의 글자가 같이 표시되서 그런거 같은데..

**Comment by ajh1000** [comment]
1. 디버깅 캡처 1
![캡처1](https://imgur.com/uBKKCbN.png)
2. 디버깅 캡처 2
![캡처2](https://imgur.com/RCGmYON.png)

```if (!node.className.includes('-translated'))``` 이 부분을 통과하는것 같다고 말한 부분은 보니까 그 전에 있는 if문 ```if (computedStyleCheck && computedStyleCheck != 'none') {``` 에서 computedStyleCheck 값이 'none' 이라 if문 안으로 안들어감. 

다른 문제인듯.

**Comment by ajh1000** [comment]
아.. 상한해방 탭을 번역할때는 정상인데, 이후 상한해방하기 버튼을 번역할때 문제가 생기는것같네. 정리해서 글쓰겠음

**Comment by ajh1000** [comment]
![캡처](https://imgur.com/kh32NJE.png)

```style.innerText = ".btn-evolution.active::after {content:'상한해방하기' !important}```  로 스타일이 생성되서 ```document.head.appendChild(style);``` 해버리니까 스타일이 일괄적용되버린거네. 일단 원인은 이런것같음.

**Comment by ajh1000** [comment]
ㅇㅋ 
변경 전 : ```style.innerText = `.${classNames}-translated::after{ content: "${translatedText}" !important; }`;```
변경 후 :```style.innerText = `.${classNames}-translated::after{ content: "${translatedText}" !important; }`;```

이제 중복 안됨.

**Comment by sidewinderk** [comment]
간단한 문제였네. 수고했음!
내가 수정해서 push 해도되는데, 이왕이면 수정한 사람 내역이 남게 저거만 포함해서 PR 해줄 수 있음?
마찬가지로 gbfTrans.js 와 gbfTrans_test.js도 해당 부분 수정해서 PR해주면 좋겠음.

**Comment by ajh1000** [comment]
ㅇㅋ gbfTrans.js 랑 _test.js 도 수정해서 PR하겠음

**Comment by ajh1000** [comment]
ㅇㅋ gbfTrans.js랑 gbfTrans_test.js는 추출 관련 코드를 주석처리한 파일인것같음. content.js랑 일일히 비교하며 추가된 부분들을 알맞게 수정해서  PR함.

**Comment by sidewinderk** [comment]
gbfTrans 와 gbfTrans_test 는 크롬확장없이 js 만 불러와서 돌리는 환경(아이폰 등)에서 사용하는 스크립트로서, '크롬확장'과 관련된 파트를 전부 주석처리해서 사용함.

추가로 _test.js는 기능 추가 직후에 잘 작동하는지 테스트 하는 용도로 사용되고, test가 없는게 본유저들이 사용하는 코드임. 차이는 _test.js 는 제일 위에 있는 `var isVerboseMode = false;`가 `true`로 되어있음.

자세한 변경 내용은 PR에 코멘트 달겠음.

**Comment by sidewinderk** [comment]
해결된 것 같이 보이므로 닫아두겠음.
