### ISSUE TITLE
archive.csv 문제점

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#17]
#### 버그
1. 마이페이지로 이동
2. 추출 모드 키고 전체 텍스트 가져오기
3. 복사버튼 눌르고 구글 스프레드 시트에 붙여넣기하기
4. 쉼표가 들어가있는 문장들은 kr칸으로 침범함.

문제는 일본어에서는 쉼표가 '、' 이런 문자라서 구글 스프레드 시트는 이 문자도 자동으로 구분해버림.

그래서 PushCSV함수에에 코드 추가해봄

```
else if (text.includes('、')){//일본어에서는 쉼표를 이렇게 표현하나봄. csv파일에 이 문자가 있을때 자동으로 구분해버림.
        array.push('"' + text + '"'); 
    }
```
이렇게 하고 텍스트 가져와서 구글 스프레드 시트에 붙여넣기해보니까 따옴표가 사라져있음.

아무래도 csv 파일에서 첫번째 열에있는 따옴표는 자동으로 삭제시키나봄.

### 해결책
첫번째 열에 따옴표가 있을경우 자동으로 삭제처리 안하게끔하는 다른 방법을 찾아봐야할듯

**Comment by ajh1000** [comment]
확장자는 csv로 냅두고 탭으로 구분해보니까 탭으로 구분되네. 확장자는 건드릴 필요없을듯

**Comment by sidewinderk** [comment]
해당사항은 csv의 사양이며 버그라고 볼 수 없음.

먼저, 추출모드에서 나온 텍스트를 바로 구글스프레드 시트에 복붙하면 안됨.
https://youtu.be/Wxxb0DTpwug
지난 추출 시연연상에서 볼 수 있듯이, csv파일을 구글 스프레드시트의 '가져오기' 기능을 이용해서 불러오는 것이 올바른 사용법임.

여기에는 몇가지 고려사항이 있는데,
1. 원문이 웹기반의 소스이기 때문에 tsv파일 포맷을 사용하기 어려움.
원문중에 tab으로 띄어쓰기를 여러번한 문장이 포함되기도함.
그럴경우를 tsv에선 쌍따옴표로 묶어주는 방식을 취하는데, 이는 쉼표한 포함된 csv에서도 같음.

2. csv에서 쉼표나 쌍따욤표가 포함된 문장은 자동으로 쌍따옴표로 한번 더 묶어주게됨.
예를들면 12,34 가 첫번째 칸이고 두번째 칸이 5678 일 경우, csv를 text파일로 열어보면
"12,34",5678 과 같은 방식으로 쉼표가 들어간 문장을 쌍따옴표로 묶어주게됨.
이를 단순히 text만으로 복사하여 스프레드에 붙여넣게되면 ""가 포함된 채로 붙여넣기가 되므로 반드시 불러오기를 통해 csv포맷으로 불러와줘야함.

위 방식을 통해 csv포맷으로 모든 종류의 텍스트를 다룰 수 있음.

**Comment by ajh1000** [comment]
아 가져오기 기능이 올바른 사용법.

지금 다시 가져오기로 하니까 정상적으로 붙여지네. ㅇㅋ.

이슈는 닫겠음.

추가로 PushCSV 함수의 기존 코드에 살짝 문제점이 보여서 살짝 수정했음. 좀따 PR하겠음
