### ISSUE TITLE
게임 내 설정 화면에서 이미지 번역 1개 잘못된 부분

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#19]
![캡처](https://imgur.com/kaAgyoA.png)

메뉴버튼 - 설정 누르면 나오는 화면에서 이미지 번역이 이상하게 적용됨.

**Comment by sidewinderk** [comment]
이 부분은 현재 내 미스가 맞음.
해당 이미지가 같은 파일명에, 페이지별로 다르게 불러오는 것 같은데 추후에 파일명 업데이트 하겠음.

**Comment by ajh1000** [comment]
아 알겠음!

**Comment by ajh1000** [comment]
이건 해결된것같아보임. 닫아도될듯?
