### ISSUE TITLE
같은 문장이 여러 번 중복으로 추출되는 현상

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#2]
이건 텍스트 창을 마우스 클릭질 할때마다 `var sceneObserver = new MutationObserver(function(mutations) {` 해당 코드가 여러번 실행되서 storyText 배열에 계속 추가되는 현상임. 이건 storyText_Index값과 prt-log-display 창의 자식 갯수 값을 비교하는 코드로 해결가능. 내가 커밋한 기록 중에서 최근 커밋 중에 이 부분 해결한 코드 있으니까 금방 해결 가능할 듯.

**Comment by sidewinderk** [comment]
var LogLength = mutation.target.children.length;
와
if (storyText_index < LogLength)
로

필터링 중인 것으로 생각하고, 추가해두었음.
시험삼아 중복 텍스트를 불러왔던 퀘스트를 추출해봤는데 해결된것으로 보아 일단 닫아두겠음.
