### ISSUE TITLE
이미지 번역 속도

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#21]
컴퓨터로 했을때나 핸드폰으로 했을때나 동일하게 My Page의 이미지들 번역하는 속도가 느린데, 하이퀄리티의 png파일을 다운로드하려하니까 그렇게 느린게 아닌가라는 추측을 해봄.

반면에, 로컬 DB를 이용하면 속도가 실시간급으로 바뀌는데 핸드폰은 로컬 DB사용 체크하고 해보면 이미지 번역이 안됨.  어쩔수없이 핸드폰은 온라인DB사용을 해야되나봄.

그래서 절충안으로 온라인DB에 있는 이미지들을 리사이징해보면 어떨까?

https://www.reduceimages.com/

구글링하다가 발견한 이 사이트로 width, height 크기를 50% 줄여서 해보니까 7백 KB까지 줄여지던데, 깃허브에 한번 리사이징한 이미지 올려서 속도가 빨라지는지 테스트해보는것에 대해 어떻게 생각함? 퀄리티가 너무 떨어질려나?

**Comment by sidewinderk** [comment]
크롬확장 커뮤니티에 질문을 해보니 `chrome.storage.local` 말고, IndexedDB 같은걸 써보라는 의견이 있었음.
찾아보니 파일등도 관리가능한 방법일 것 같은데 안 써본거라 공부해서 만들어야함. 따라서 좀 장기적 관점의 업데이트가 될듯.

이걸 확장해서 생각해보면, 기존의 DB(csv들 및 images)를 확장 내부에서 IndexedDB 등으로 저장해서 불러오는 DB를 세부설정에서 하나의 옵션으로 추가할 수 있음. 온라인 DB에 업데이트가 있는지는 기동할 때 처음 fetch 하거나 주기적으로(하루에한번?,수동fetch가능하게) 확인해서 가져오고, 이후에는 저장해둔 이미지/번역DB 를 불러와서 쓰는 방법으로하면 모바일 환경에서도 데이터 소모량도 줄고 속도도 비약적으로 빨라질 듯 함.

관련해서 새 issue를 만들고 이 이슈는 닫아두겠음.

관련 링크:
https://developers.google.com/web/ilt/pwa/working-with-indexeddb
https://codelabs.developers.google.com/codelabs/pwa-indexed-db/index.html?index=..%2F..dev-pwa-training#0
https://pouchdb.com/
