### ISSUE TITLE
가이드 영상 재업로드함. 확인 요청.

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#22]
https://youtu.be/ulZk8yL8ge8 

이번엔 어떰? Good?

**Comment by ajh1000** [comment]
덤으로 구글 스프레드시트에 (임시)퀘스트_이벤트_데레마스 시트를만들어서 최신 포맷에 맞춰 작성함. 그것도 검토 부탁드림. ㄳㄳ

**Comment by ajh1000** [comment]
흠흠 그럼 영상도 만들었고, 스프레드시트 작성하는 방법도 영상에 담았으니 이제 스토리 번역에 시동을 걸어볼만 할려나 어떻게 생각함?

**Comment by sidewinderk** [comment]
깔끔한듯.
이대로 일단 시트에 업데이트하고, 다음번 글 적을 때 소개 하겠음.

한가지 맘에 걸리는건, 본 DB에 바로 가져오는 것 보다는 개개인의 시트에서 작업을 하고 본DB에는 복붙하는 방식위주로 제안하고자함. 
왜냐면 저 가져오기 메뉴에서 실수하면(세번째 스프레드시트 바꾸기 옵션) 전체 DB가 날아갈 수도 있음. 물론 경고창도 뜨고, 누구나 되돌리기로 살릴 수 있지만 실수할 여지를 남겨두고 싶지 않음.
(굳이 이 내용을 갤러리 글에 언급해서 반달성향의 유동을 자극하고 싶지도 않음)

추가로, 코드를 살짝 수정해서, 영어 혹은 일어 어느쪽이라도 번역문이 있다면 그걸 적용하게 해줘야할듯.
지금 시트에 업데이트 된 것으로 보면 영문에도 일문 번역을 넣어둔 것 같은데, 보통 번역할 때 한쪽만 하게 될테니.. 
개인적인 우선도는 일분>영문 이므로, 먼저 일문에 orig가 있는지를체크하고, 없으면 영문의 orig가 있는지를 마저 체크해서 번역문을 가져오면될듯함.

기술적으론 스토리 번역 시동을 걸 수 있을 것 같은데, 아직 한번의 밴 웨이브도 지나가지 않은 상태라 참가자나 기여자가 별로 움직이지 않을 것임. 개인적으론 화전장 밴웨이브가 지난 뒤에 고전장 끝나고 개시 글을 올리는 게 좋아보임.

**Comment by ajh1000** [comment]
ㅇㅋ 일본어로 번역한걸 밑에 있는 영문칸에도 붙여넣기 하는 작업을 없애도록 코드 수정해보겠음

코드 수정하고 수정한걸로 영상 한번 더 녹화하면 좋겠는데 내가 내일 다시 군대로 휴가 복귀라 언제 영상 녹화할 수 있을지 모르겠음 ㅋㅋ.

**Comment by ajh1000** [comment]
아 사지방에 영상 녹화하는 프로그램이 깔려있는것같네 생각해보니까. 그걸로 고전장 전까지 촬영해서 이슈에 올리겠음.

**Comment by sidewinderk** [comment]
추출만하는 사람들은 영/일문 다 추출하는게 좋으니 그대로두고, 
코드만 수정한뒤에 영상 올리거나 공지할 때 텍스트로 언급해줘도될 것 같음. 수고하셨슴.
