### ISSUE TITLE
(크롬확장) 업데이트 가능한 로컬 번역DB 옵션 추가

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#23]
번역툴의 기존 DB옵션은 크롬확장의 내부 파일시스템을 사용하는 **로컬DB**와 GitHub에서 바로 가져오는 **온라인DB**가 있었는데, 스토어앱에서는 로컬DB의 파일 시스템에 접근할 수 없어서 온라인DB 사용이 강제되었음.
이는 기능상 문제가 없으나, 이미지 파일을 포함한 모든 DB 자료를 웹페이지(GitHub)에서 다운로드 해서 사용하기 때문에 네트워크 속도가 느리거나 데이터사용의 제약이 있는 모바일 환경 등에서는 좋은 방법이 아님.

따라서, 크롬확장앱에서 온라인DB를 다운로드하여 로컬DB를 업데이트 할 수 있도록 개선하면 위의 문제를 해결 할 수 있음. 여기에는 두가지 방법을 고려해볼 수 있는데,
- 기존의 로컬DB 방식에 추가로 확장앱에서 로컬DB를 업데이트하는 옵션을 넣기
- 해당기능을 하는 새 로컬DB를 만들어, 기존의 로컬DB는 디버깅/번역QA용으로만 사용하도록하기
위 두 방법 모두 유효한 해답이 됨.

가장 이상적인 방법은 기존의 로컬DB를 업데이트하는 옵션을 추가하는 방향인데, 이 방법은 깃허브에서 zip파일로 받아서 설치한 확장과 스토어에서 받은 확장 양쪽에서 다 사용이 가능함. 
문제는 이 방법을 위해선 크롬확장에서 자체적으로 파일을 다운로드하여 로컬 파일시스템에 저장할 수 있어야하는데, 대충 찾아본 바로는 이게 안되는 것 같았음. 만약 가능하다면 당연히 이쪽 방향을 선호.

두번째 방법은 첫번째 방법이 안될 것 같기 때문에 고민중인 대안인데, 기존의 `chrome.storage.local` API에서는 파일을 관리하는게 가능할지 잘 모르겠음. 대신에 `IndexedDB` API 등의 DB API가 이 기능을 해줄 것으로 생각함.
자세한건 더 파봐야 알 것 같음. 비슷하게 PouchDB 등도 대안이 될 수 있을 것 같음.

구상중인 기능으론:
- (새 DB를 추가할 경우) 상세설정에서 DB 옵션에 해당 DB 사용옵션 추가
- DB 업데이트 주기는 대략 12시간-24시간 정도로 설정
- DB 수동 업데이트 버튼 추가, 버튼을 누른 뒤에 업데이트 결과등을 알 수 있는 텍스트가 표시되어야함.
- (새 DB를 추가할 경우) `contents.js` 파일에서 `generalConfig.origin` 에 해당하는 값을 DB path 등의 형식으로 바꾸거나 각 파일들을 불러오는 방식을 DB에서 가져오는 방식으로 수정

이 업데이트는 기능상으로 변하는 게 없기 때문에 장기적인 관점에서의 업데이트가 될 예정.

참고링크:
https://developer.chrome.com/apps/offline_apps
https://pouchdb.com/

**Comment by ajh1000** [comment]
아이디어 생각나서 써봄.

브라우저의 캐시 기능이 효과가 있는지 테스트 해보고싶음.

### [Example]
1. 확장 프로그램  popup.html 에서 "이미지 로드" 버튼을 누른다.
2. 새로운 페이지 하나가 띄워진다. 이 페이지는 sidewinderk/gbfTransKor 저장소에 있는 images 폴더안의 모든 image파일들을 하나씩 불러온다.
3. 새로운 페이지에서 로딩창 하나를 띄워서 진행 상황을 표시한다.
4. 로딩이 완료되면 완료됐다는 알람창을 띄워주고 새로운 페이지를 자동으로 닫아준다.

괜찮은것같은데 어떻게 생각함?

**Comment by sidewinderk** [comment]
컨셉은 추후에 좀 더 다듬을 수 있는데, 핵심 기능이 먼저 구현가능한지 체크해봐야함.

1. 로컬DB(캐시)에 저장
2. 로컬DB(캐시)와 원격DB 간의 비교
3. 로컬DB(캐시)를 업데이트(저장과 비슷)

이 기능이 먼저 구현가능해야, 이후에 이걸 어떻게 다룰지(유저들에게 보여주지 않고 자동으로 처리하거나 수동으로 업데이트하는 옵션을 넣거나)를 유의미하게 고민해볼 수 있을 거 같음.

**Comment by ajh1000** [comment]
로컬DB에 저장하는 방식을 좀 더 고민해보고 이게 안된다면 온라인DB에서 이미지를 더 빠르게 불러들이는 방식을 고민해보는걸로 정리할수있을것같음.

로컬DB 저장 방식은 천천히 테스트해보겠음.

**Comment by ajh1000** [comment]
저번 주에 군대 전역했음. 글고 오늘 눈 수술하느라 앞으로 일주일 동안은 작업을 못해서 담주에 복귀하면 이거부터  건드려볼 생각임. ㅇㅋㅇㅋ!

**Comment by sidewinderk** [comment]
@ajh1000 전역 축하함! 나도 요근래 바빠져서 크게 손을 못대고있었는데 다시 작업해주니 힘내보겠음.

**Comment by sidewinderk** [comment]
의도했던대로 업데이트 된 것 같음. 닫겠음.
