### ISSUE TITLE
로그인 보너스 및 스토리 인트로 등의 애니메이트된 이미지 치환

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#26]
로그인 보너스, 스토리 인트로/엔딩 등에 쓰이는 애니메이션 이미지의 번역에 대한 건.

예를들어, 게임을 처음부터 시작하여, 주인공 성별 선택 직후에 접하는 튜토리얼3(http://game.granbluefantasy.jp/#tutorial/3)에서는 http://game-a1.granbluefantasy.jp/assets/img_mid/sp/cjs/opening.png?s=d391d3991943a37e2f5004fe212cdcfa 이 이미지에 있는 텍스트를 사용해서 애니메이션으로서 사용함.

현재 이 이미지를 치환하는 방법에서 막혀있음.

해당 페이지의 js파일 http://game-a3.granbluefantasy.jp/assets/1593054979/js/model/manifest/opening.js 에서는, Model.extend를 통해서 id:"opening" 에 대한 오브제트를 정의해주고 있는 것 같은데, backbone.js 를 써본적이 없어서 어떻게 덮어씌워줘야할지 모르겠음.
단순히 console에서 `Backbone.Model.extend` 로 덮어씌워주는 것으로는 변화가 없는 것 같음.
다음으론, `exportRoot` 라는 오브젝트의 내용물을 덮어씌우는 것인데 콘솔에서 `exportRoot.opening_text_1.instance.La.currentSrc` 혹은 `exportRoot.children[29].instance.La.currentSrc` 값이 바로 해당 이미지 소스 파일에 대한 주소라서 이걸 for loop 등으로 덮어씌우면 되지 않을까 싶었는데 단순히 `currentSrc = 새 주소` 방식으로는 적용되지 않는 듯.

**Comment by ajh1000** [comment]
![1](https://imgur.com/dB2zFAH.png)

아무리 해봐도 안되서... 떠오른 방법은 canvas 위에 그냥 그리는 방법을 생각함. 일단 캔버스랑 context 가져오는건 성공했으니까 이제 그냥 그려주는 방법을 공부해보는게 빠르지않을까 생각함 ㅋㅋㅋ... 어떻게 생각함?

**Comment by sidewinderk** [comment]
흠.. 결국 새로 그리는 걸 공부하는 과정에서 기존 스크립트를 수정할 수 있는 방법이 나올 것도 같은데, 일단은 잘 모르겠으면 다른 급한거 위주로 처리하고 일단은 보류해두자.

**Comment by ajh1000** [comment]
이미지 치환 성공한것같은데 봐줄수있음? 영상으로 녹화함.

https://youtu.be/ZY6tOl4_8eM

이미지 request URL을 임의로 리다이렉션하는 식으로 해보니까 이미지 치환에 성공함.

밑의 코드만 추가했음.

```

chrome.webRequest.onBeforeRequest.addListener(function(details) {
    console.log(details.url);
    if (details.url.includes('game-a1.granbluefantasy.jp/assets/img/sp/cjs/opening')) {
        console.log('found!~!~~!~: ' + details.url);
        return {redirectUrl: 'https://pbs.twimg.com/profile_images/733409018471972865/F_RMK5km.jpg'};
    }
}, {
    urls: [ "<all_urls>"], // or <all_urls>
    types: ['image'],
}, [
    'blocking'
]);
```

chrome extension 에서 제공하는 webRequest API 를 쓴거라서 Tampermonkey 를 사용하는 사람들은 해당 API에 접근 못한다는 단점이있음. 

결국 확장 프로그램 사용자들만 완벽하게 이미지 번역이 되는것이 현황임.

Tampermonkey 사용자들도 해당 기능을 이용할 수 있는지 함 연구해보겠음.

**Comment by sidewinderk** [comment]
오 괜찮은거 같은데? 
내가 전에 작업해둔 스토리 이미지 커밋해뒀는데
https://github.com/sidewinderk/gbfTransKor/blob/master/images/story/tutorial/openning.png

위 이미지로 리다리이렉션 해 봐줄 수 있음?

여담으로, 전에 이미지 주소 호출 request를 가로채서 온라인DB에 해당하는 주소로 치환하는 방법을 고려해봤었는데, 
기존의 웹페이지를 일단 완성하고, 텍스트나 이미지를 치환하는 과정과 달리 request 단계에서 관여를 하게되면 
보안적으로 어딘가에서 막힐 것 같아서 시도하다가 말았었는데, 지금 위와같이 해서 특별한 에러나 경고없이 작동된다면 템퍼몽키등을 사용하는 자바스크립트 기반에도 같은 방식을 적용할 수 있을지도?

**Comment by ajh1000** [comment]
![1](https://i.imgur.com/NYksFlm.png)

성공적으로 적용됨. 

근데 그대로 링크 붙여넣기 하니깐 안됐음. 

님이 준 링크 그대로 붙여넣으니까 CORS 정책에 위반된다는 콘솔 에러가 뜨면서 안됐음.

그래서 님이 준 링크의 이미지에 오른쪽 마우스 클릭하고 이미지 주소 복사 메뉴 눌러서 붙여넣기하니까 적용됨.

밑의 이미지처럼 링크를 저렇게 하니까 잘됨.

![image](https://user-images.githubusercontent.com/22585023/98428995-7658d700-20e7-11eb-9117-44c0298ef29c.png)

근데 님이 만든 이미지는 사이즈가 작아서 좀 깨져보였고, 1024x2048 이미지로 늘리니까 완전 잘보임.

**Comment by ajh1000** [comment]
모든 이미지 번역을 리다이렉션으로 해결하는건 어떻게 생각함?

최근에 있던 퍼포먼스 향상 커밋에서도 아직 근본적인 이미지 번역 문제는 해결이안됐는데.

리다이렉션으로 구현하면 mutation으로 퍼포먼스를 갉아먹을 일도 없어지고 이미지 번역 지연 문제도 없어질듯.

그렇게되면 mutation 은 archive랑 스토리 텍스트만 감지하게되니까 부담이 훨씬 줄어들어서 퍼포먼스가 좋아질것같음.

걱정되는 부분이라면 리다이렉션으로 구현하게되면 밴 당할 확률이 높아지나? 

이론적으로 생각해봤을때 밴의 원인이 될려나 같은 생각이 듬.

**Comment by sidewinderk** [comment]
기본적으로 동의함. 
Tree로 모든 elements 에 대해서 loop 를 도는 게, 퍼포먼스적으로 아주 비효율적인 일이고, 거기에 이 동작을 모든 조작에 대해 매번 새로 실행하는게 영향이 가장 큼.
다만, 이 기능은 단순히 번역텍스트 처리하는 것 처럼 페이지 로딩이 끝난 뒤에 후처리를 하는게 아니라 페이지 로딩 중에 작업을 하는 방식이기 때문에 운영국 측에서 태클을 걸자면 걸 수는 있을 수도 있다고 생각됨.

따라서, 이 기능을 바로 기본 기능으로 대체하는 것 보다, 옵션에 experimental 로 넣어서 일부 유저들에게 pilot 으로 적용하고 추이를 살펴보면서 개발하는게 좋을 것 같음. 당연히 나는 일단 켜도 테스트 해 볼 생각임.

**Comment by ajh1000** [comment]
아하 알겠음!

리다이렉션 기능은 확실히 악수가 될수있을것같음. 

밴에 대해서 좀 찾아봤는데 그랑블루 판타지의 안티치트 코드를 발견했음.

https://www.reddit.com/r/Granblue_en/comments/4uj4nx/anticheat_update_725/

4년전 코드지만 지금 다시 내가 확인해보니까 달라진점이 조금은 있는것같음. 자세히는 모르겠음. 밑에는 현재 안티치트 코드임. 

![1](https://imgur.com/6Yb57tc.png)

개발자 도구 -> network 탭에서 /ob/라고 검색했을때 뜨는거 한개가있는데 여기에서 맨 밑에 payload 부분을 보면 q값이 1400으로 뜸. 이 값은 안티치트 목록에 기록되있지 않은 정상적인 코드임. 

우리 번역툴은 안티치트에 직격으로 위반되는 코드는 쓰고있지 않는것으로 판단됨.

근데 리다이렉션을 해서 이미지를 블락시켜버리면 서버측에서는 우리가 모르는 안티치트 코드가 돌아갈까봐 두렵긴함. 

그래서, 내가 안전하게 번역되게끔 이미지 번역 기능은 샤니마스 한패 번역 소스 (https://github.com/biuuu/ShinyColors) 를 참고하고싶은데 어떻게 구현되있는지 하나도 모르겠어서 따라해보기 힘듬. 

암튼 이미지 번역 기능은 지금 상황을 유지하고 더 나은 기능을 구현하게되면 다시 찾아오겠음.

**Comment by sidewinderk** [comment]
개인적으론 image request 정도는 redirection 해줘도 괜찮을 것 같은데, 말한대로 보수적으로 접근하는게 맞음.
따라서 해당 기능을 테스트하고 싶다면 실험실 기능에 넣고 기본적으로 작동하지 않게하고, 누군가 켜려고한다면 경고창을 한번 더 띄우는 등의 추가적인 보험 절차가 필요함.

**Comment by ajh1000** [comment]
![1](https://user-images.githubusercontent.com/22585023/99019869-ad743000-25a0-11eb-867c-c58fd37eca88.PNG)

빨간색 네모박스 친 저 부분은 DOM 객체로 그려지는게 아닌가봄. 

캔버스 위에 이미지와 글자가 함께 렌더링 되는것같음.

저런 글자들은 Network 탭에서 보이지도 않아서 리다이렉션이 불가능함.

문제는 캔버스에 렌더링한것들을 클라이언트 사이드에서 어떻게 번역해야하는지 전혀 알수없겠는것. 

일단 이런 부분들도 여기다가 메모해두고 나중에 알아보기.

**Comment by ajh1000** [comment]
컴퓨터 고장나서 as보내고 다음 주 즈음에 돌아올 예정. 

그동안 만들엇던 부분들은

1. 캔버스 이미지, 캔버스 텍스트(전투 화면의 스킬 텍스트) 번역 기능
2. 스토리 텍스트 추출할때 f12 안누르고 바로 추출하게 함.

두 개 기능 모두 순수한 자바스크립트로만 짜서 갠차늘듯.

### 전투 화면 캔버스 텍스트 번역 화면
![0HuZP4J](https://user-images.githubusercontent.com/22585023/100755200-445d3b00-342f-11eb-8282-3c374621bfb6.png)

담주에 PR해보겟음.

간단하게 만들어봤음. 

Image, XmlHttpRequest, CanvasRenderingContext2D 에서 사용하는 기본 함수들의  prototype을 override해서 인터셉트 했단 느낌. 이런 아이디어를 이제 발견하다니 암튼 다행인듯.

**Comment by sidewinderk** [comment]
오호 같은 방식으로 주인공 파티의 버프효과등도 적용가능 할 것 같네.
이게 막혀있던 제일 큰 부분 중 하나였는데, 여기까지만 적용해줘도 실질 전투 관련 번역 기능은 대부분 완성되었다고 볼 수 있을듯.

PR 기다리겠음.

**Comment by ajh1000** [comment]
혹시 이미지 파일 하나만 수정해줄수있음? 

요청 파일은 /story/tutorial/openning.png 

1. 이 파일의 이름을 openning.png 에서 opening.png로 수정
2. 1024x2048 사이즈로 늘리기

까지만 하면 오프닝 이미지는 정상 적용될것같음. 

아직 나머지 기능들은 더 개발중인데 거의 다 된듯함. 요번 주 내로 올려보겠음.

**Comment by sidewinderk** [comment]
파일명 수정했음.
그런데 이 파일이 원본이 이 해상도인 걸로 기억하는데, 굳이 사이즈를 바꿀 필요가 있을까?

+ 튜토리얼에서 유저명을 적용시키기 위해 제외했던 `translate_StoryText`함수의 `if (userName.length > 0)` 체크를 다시 활성화해뒀음.
스토리 번역이 정상적으로 작동하지 않는 버그가 있었음.
https://github.com/sidewinderk/gbfTransKor/commit/ffd21de3c64f8db9d90c15426a38f4f55792ffa3#diff-15c947723c169a1240ecef5c9dba3c267382cbe0ba946365aa6bc2e37f68fe9d
이부분은 tutorial 인지 확인해서, tutorial 일 때만 적용하는 방식으로 업데이트 해야할듯.

**Comment by ajh1000** [comment]
![1](https://user-images.githubusercontent.com/22585023/102440745-28c77680-4064-11eb-8445-46044dc88f91.png)
흠 그게 내 컴퓨터에서는 깨져보임.

![2](https://user-images.githubusercontent.com/22585023/102440749-29f8a380-4064-11eb-8935-32ba811713ab.png)
해상도를 늘렸다 줄였다 해봐도 원본 이미지 해상도는 1024x2048로 보이는데 기기 차이가 있는걸까?

translate_StoryText 함수는 확인했음. 수정해보겠음.

**Comment by sidewinderk** [comment]
오 그렇네 지금 확인해보니, 해상도가 업데이트 된건지 1024로 다운받아짐. 새로 작업해서 올려두겠음.

**Comment by ajh1000** [comment]
감사감사

**Comment by sidewinderk** [comment]
이미지 업데이트함.

**Comment by ajh1000** [comment]
많이 늦어지고있는데 미안함.

이리저리 테스트하다가 버그가 하나있어서 살짝쿵 수정 요청함.

일단 지금 계정 생성 후에 보이는 opening.png는 이미지 크기가 768x1536 임.

그래서 이게 좀 웃긴데 암튼 /story/tutorial/opening2.png 로 사이즈를 768x1536 로 줄인 버전을 업로드 해줄수있음?

**Comment by sidewinderk** [comment]
내 생각엔, 이게 기동시의 해상도에 따라 다른 사이즈의 파일을 불러오는게 아닐까싶음.
몇가지 환경에서 체크해보고 준비해서 올려보겠음.

**Comment by sidewinderk** [comment]
확인결과, 게임 설정에서의 해상도 옵션에 따라서 이미지 주소도 바뀌고 해상도도 바뀜.

http://game-a1.granbluefantasy.jp/assets/img/sp/cjs/opening.png?s=8071ab954bf0ac249eac4d4d8171726a
http://game-a1.granbluefantasy.jp/assets/img_mid/sp/cjs/opening.png?s=d391d3991943a37e2f5004fe212cdcfa
http://game-a1.granbluefantasy.jp/assets/img_low/sp/cjs/opening.png?s=20c5157ac7733ffa026b53d0963d2f6a

각각 위의 3가지 경우였는데, 제일 위가 고화질 설정일 때의 이미지이고, 게임을 처음 시작했을 때 기본 값은 표준, 가운데 사이즈가됨.
그래서 새 디바이스에서 튜토리얼을 실행했을때 이미지가 가운데 이미지가 로드 되었던 것 같음. 
(동시에 번역툴 사용을 위해 고화질로 올린 상태에선 위의 이미지가 불러와졌던 것)

일단 가운데 새 디바이스 기본값 이미지로 작업해서 opening2.png 로 올려뒀음.

동시에, 좀 더 중장기적으로.. 이미지 해상도 설정에 따라 이미지를 어떻게 처리할지 고민을 해보긴해야할 것 같음. 이건 따로 이슈를 열겠음.

**Comment by ajh1000** [comment]
오 URL에 이미지 해상도가 저렇게 적혀있었구나. 고생하셨음.

지금 만들고있는 이미지 번역 코드에서는 이미지 url값을 얻어오면서 번역하고있어서 이번 경우는 해볼만할듯.

url이 opening.png를 포함하면서 img_mid를 포함하고있는 url이면 지금 업로드해준 opening2.png를 적용하게끔 하면 될것같음.

그러면 opening2.png를 opening_mid.png로 바꾸는게 깔끔할려나 암튼.

지금은 튜토리얼 페이지 번역에 버그들이 넘나 많아서 해결하느라 늦어지고있음.

이제 하나만 더 해결하면 끝이니까 내일이나 내일모래에 정리해서 올리겠음.

**Comment by ajh1000** [comment]
url 적용에 애로사항이 살짝 있음.

깃허브 디렉토리 /story/tutorial/opening.png 로 해놓은것을 /img/sp/cjs/opening.png로 바꿔줄수있음?

추가로,

/img_mid/sp/cjs/opening.png
/img_low/sp/cjs/opening.png

까지 깃허브에 추가해주면 정말 감사하겠음 ㅠ.

image.csv 구글 스프레드시트는 내가 두 줄 추가해보겠음.

이러면 하드코딩 안하고 넘어갈수있어서 좋을것같음. 혹시 해줄수있음?

**Comment by ajh1000** [comment]
아아 아니다. 내가 잘못이해했네. 

깃허브 디렉토리 자체를 안바꿔도되고,  파일명만 바꿔주면됨. 

mid 해상도는 opening_mid.png, low 해상도는 opening_low.png로 해서 추가해주면됨.

그러면 내가 image.csv 파일에서 

orig를 /img_mid/sp/cjs/opening.png 로 두고
kr 을 story/tutorial/opening2.png 로 하면 적용되겠음.

**Comment by sidewinderk** [comment]
일단 opening_mid.png 와 opening_low.png를 추가했음.

추가로 이미지 추가 작업을 좀 더 직관적이고 단순하게 하기 위해서,위에서 제안한 것 처럼 
전체 이미지 경로를 img/sp, img_mid/sp, img_low/sp 아래에 두는 방식으로 폴더를 개편해보는 건 충분히 고려해볼만 할 듯.

**Comment by sidewinderk** [comment]
@ajh1000 잘 진행되고 있음? 막힌 부분이 있으면 공유해주면 같이 뜯어 볼 수 있을듯.

**Comment by ajh1000** [comment]
요즘 토익 공부하느라 개발하는데에 살짝 번아웃이 와서 다른 일들은 쉬고있었음.

내일부터 다시 시작해봄.

남아있는 기능들은 

1. 전투 텍스트 추출
2. 1번 기능 완성되면 최종적으로 gbfTrans.js 수정.

일단 지금까지 개발한 기능은 indexedDB로 내장DB를 구현하고 적용되게함. 특히 이미지 번역 속도는 엄청 빨라짐.

[링크](https://github.com/sidewinderk/gbfTransKor) 여기서 다운받아서 테스트할수있음. 

지금 고민사항은 DB 업데이트 방법임.

일단 내가 생각한 DB 업데이트 타이밍은,

PC 버전이든 모바일 버전이든 매일 0시가 지났을때, 게임 페이지에서 새로고침을 누르면 DB 다운을 시작하기.

이거임. 

여기서 진짜 문제점은 번역 이미지 리소스를 다운할때 걸리는 시간이 10 ~ 20초 사이로 걸리기 때문에 매일 게임 실행했을때 사용자 입장에선 10 ~ 20초를 기달리고 게임을 하게되므로 귀찮아할것같음. 

이 부분은 위의 링크에서 다운받아서 [번역하기] - [이미지 번역문 업데이트] 버튼 클릭해보면 걸리는 시간을 볼수있음.

암튼 그래서 떠오른 방법은 

1. 이미지 업데이트 같은 오래걸리는 업데이트는 일주일에 한번만 하게할지 고민중임.

2. 아니면 있을것같진 않은데 깃허브에서 최근에 commit 된 파일들을 보여주는 API같은게 있다면 변경된 이미지 파일만 다운로드하게할수있으면 좋을것같음. 

결론은 새로 바뀌게되는 번역툴에서 이미지 업데이트 방식을 어떻게 할지 고민해보면 좋을것같음.

**Comment by sidewinderk** [comment]
이 이슈도 거의 해결된 것으로 보이니 일단 닫아도 될 것 같음.
