### ISSUE TITLE
온라인 DB 스토리 시트 업데이트 

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#27]
https://docs.google.com/spreadsheets/d/1LQiu94RhA5gRlcOja0oMrtRKfql14yCvJZlpa25xvi0/edit#gid=1494134311

번역에 기여하고싶은 사람들은 확장프로그램 안깔아도 구글 시트만 보고 번역할수있으니까 접근성을 높이도록 업데이트해봄.

새로 생성한 시트는 (임시)이벤트 스토리 번역 진행률, (임시)메인 스토리 번역 진행률 2개. 

접근성은 어떤지 등등 어떤거같음?

**Comment by ajh1000** [comment]
https://docs.google.com/spreadsheets/d/1DpEWIt5SiicxhN1v8pdQyikOme6gzvFvd6lRpYqeh70/edit#gid=1607057200

샤니마스 UI 한패하는 시트를 보면 이미지 번역도 사람들이 참여하도록 만들었는데 우리도 이런식으로 하면 좋지않을까?

**Comment by ajh1000** [comment]
마지막으로, 스토리 번역하게되면 이벤트 스토리 하나당 시트 1개를 차지하게되는데 그러면 우리 DB에 시트가 ㅈㄴ 많아져서 곱창날것같음. 

시트의 무한 증식을 막기위해 "quest_MainStory",   "quest_EventStory",     "quest_FateStory",    "quest_OtherStory" 

총 4개 시트를 만들어서 각각의 시트에 해당하는 번역 작업들을 추가해나가는게 좋지 않을까 생각함. 

DB를 정리하고 넘어가기에 좋은 타이밍인것같음.

**Comment by sidewinderk** [comment]
> https://docs.google.com/spreadsheets/d/1LQiu94RhA5gRlcOja0oMrtRKfql14yCvJZlpa25xvi0/edit#gid=1494134311
> 
> 번역에 기여하고싶은 사람들은 확장프로그램 안깔아도 구글 시트만 보고 번역할수있으니까 접근성을 높이도록 업데이트해봄.
> 
> 새로 생성한 시트는 (임시)이벤트 스토리 번역 진행률, (임시)메인 스토리 번역 진행률 2개.
> 
> 접근성은 어떤지 등등 어떤거같음?

캐릭터 리스트 시트와 같이, 기본적으로 전체 진행률이나 진행된 파트와 남아있는 파트를 한눈에 볼 수 있는 시트를 준비하는건 괜찮은 생각 같음.

이 시트에 정리할 단위에 대해선, 메인스토리가 1(1-1,2,3,4),2(2-1,2,3,4) 이렇게 나가니까, 1화 단위로 하는게 좋을 것 같음.
이벤트의 경우 오프닝-1-2-3-4-5-6-엔딩 총 8개의 칸을 차지하는 형태로?

그리고 아래에 언급한대로, 시트를 메인/이벤트/페이트/기타 로 나누는 것도 동의함. 이경우, 내가 싱크하는 스크립트를 좀 손봐야겠네.
이미지 번역도 샤니한패 시트처럼 하는게 괜찮을것같네, DB시트처럼 자동화하기는 어렵고 내가 담당해서 업데이트해주는 것으로 해야겠다.

제안 감사함.

**Comment by sidewinderk** [comment]
제안대로 일단 4개로 쪼개서 만들었는데, 자세한건 따로 갤러리에 공지하겠음.

고로 이 시트는 일단 닫아두자.
