### ISSUE TITLE
이벤트 스토리 시트 문제

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#28]
이벤트 스토리 시트에는 2장, 3장 번역문이 없는데 해당 스토리 플레이해보면 적용됨. 

그리고 1장 재생했다가 2장 재생하고 3장 재생하면 가끔 텍스트들 순서가 뒤죽박죽 적용되는 버그도  발생함. 

일단 2장, 3장 번역문이 어디서 긁어오는지 조사해보고, 번역문 적용 코드들을 다시 점검해보겠음.

테스트는 영어판으로 실행함

**Comment by ajh1000** [comment]
원래는 이런 일이 없었는데 버그가 발생하네.

1장 재생하고 바로 뒤로가기 버튼 눌르고 2장 재생하면 그때부터 번역문이 적용안되는 버그가 발생함.

그런데 1장 재생하고 바로 뒤로가기 버튼 눌르고 새로고침한다음에 2장 재생하면 번역문 정상 적용됨.

심지어 4장 까지 새로고침하면서 재생하면 정상 적용됨. 좀더 알아보겠음.

**Comment by ajh1000** [comment]
```

    var reservedData = [];
    var jpStartIndex = 0,
        engStartIndex = 0;
    
```

이 코드를 translate_StoryText 함수 안에 넣어서 매번 업데이트하게 하면 더 이상 버그가 발생안함. 

그냥 매번 reservedData 변수를 업데이트 하게 하는게 역시 안정적이구나. 다음 커밋때 반영하겠음. 

좀더 테스트해보고 이상 증상 일어나면 더 적겠음

**Comment by sidewinderk** [comment]
해당 변수들이 함수 밖에서 사용되지 않는다면, 안으로 넣는게 좋을 것 같음.

**Comment by ajh1000** [comment]
음 그런거같음 일단 오늘은 더이상 컴터 못하고, 내일 이어서하겠음. 그리고 혹시 이벤트 스토리 시트에 없는 내용들이 적용된 이유를 혹시 알고있음?

**Comment by sidewinderk** [comment]
PC(엣지브라우저)에서 2-1,3-1확인해봤는데 그대로 원어로 나옴.
마찬가지로 모바일(Alook-iOS,키위-안드로이드)에서도 마찬가지로 원어로 잘 나오는 듯함.

**Comment by ajh1000** [comment]
아 내가 착각함 ㅋㅋㅋ 2장 시트를 1장 2에피소드 번역으로 착각함. 

그래서 1장 2에피 재생할때마다 "아 왜 번역이 돼있지?" 혼자 이 생각했네 ㅋㅋ 

이 이슈는 닫아도됨. 코드 수정 사항은 나중에 저녁에 올리겠음
