### ISSUE TITLE
이름 창이 잘못 번역 되는 현상

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#3]
이 부분은 디버깅을 못해봐서 모르겠지만 다른 문제들을 빠르게 해결하고 알아보겠음.

**Comment by sidewinderk** [comment]
해결되었음.

원인은 기존 번역 추출방식과 새 번역 적용방식이 달라서였는데, 
기존 번역 추출에서는 똑같은 텍스트(삐냐삐냐 혹은 .... 등)가 나오면 생략하도록 짜뒀었음.
하지만 새 적용방식에서는 똑같은 텍스트와 관계없이, 텍스트가 나온 순번대로 치환하기 때문에 생략된 텍스트가 한칸씩 밀려서 나타나던 현상이었음.

새로 텍스트를 추출해서 번역문을 적용하는 것으로 해결됨.

한가지 의아한 점은, 새 추출 방식에도 isIntempDB 라는 변수로 임시 Array에 기존에 텍스트 안에 같은 내용이 있으면 제외하도록 해뒀는데, 무시하고 들어가고 있는 부분인듯.
이부분은 나중에 이상하면 지워도 될듯함.

이 문제는 닫도록하겠음.
