### ISSUE TITLE
이름 추출 기능 문제점

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#35]
에피소드 재생하면 재생과 동시에 해당 에피소드에 등장하는 모든 인물들의 이름이 추출되게끔 만들었었는데 이게 일부분만 추출되는 현상이 발견됨. 

나중에 보고 수정하겠음.

**Comment by sidewinderk** [comment]
현재 정상 작동하는 것으로 보임.
다만, 중복 추출을 방지하기 위해 상세설정-추출옵션-이미 번역된 원문제거 가 활성화되어있을 때는 이름도 기존 dict 를 돌려보고 있으면 스킵하는 방식으로 개선해줘도 좋을듯.

**Comment by ajh1000** [comment]
오 다음 PR때 해보겠음.

**Comment by ajh1000** [comment]
아 깜빡했네. 다음 PR때 다시 하겠음.
