### ISSUE TITLE
튜토리얼 이미지 추가 요청

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#37]
원본 이미지 링크 : http://game-a.granbluefantasy.jp/assets/img_mid/sp/raid/parts_btn-sa6037625f2.png

튜토리얼 전투 화면 :

 ![링크](https://imgur.com/SJpcnKo.png)

여기서 회복, 오의연출 자동, 오의연출 스킵 버튼 3개만 번역되면 좋겠음. 

내가 김프 이미지툴로 어떻게 해볼려는데 회복 버튼만 쉬웠고 나머지 버튼은 어려웠음. 

심지어 회복 버튼 잘라내서 붙인것도 퀄리티가 떨어짐. 자세히보면 테두리에 이상한 색깔이 있음.

이미지 번역은 내가 잘 못하겠어서 도움 요청함. 

계정 생성부터 시작되는 튜토리얼 화면부터 번역 해보고있는데 문제점들이 몇 개 보여서 고치고 있는중이였음.

**Comment by sidewinderk** [comment]
적용함.
