### ISSUE TITLE
스토리 텍스트에서의 주인공 이름 치환

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#4]
그랑블루 판타지 스토리 텍스트에서는, 유저의 이름을 가져와서 스토리에 넣어주는 기능이 있으나, 
현재 번역 스크립트 치환에서는 지원되지 않고 있음.

잠정적으로 번역문에서는 [グラン] 이라고 표시해 둘 예정이나, 궁극적으로는 번역문을 적용할 때 주인공 이름을 가져와서 바꿔주는 기능이 필요함.

이 기능을 위해선, 먼저 자바스크립트 상에서 유저의 계정명을 가져오는 부분을 알아낼 필요가 있음.
(아마 게임 소스에 있을 것으로 생각되나, 아직 찾지 못했음)

참고로, Game.userId 를 통해 현재 유저의 숫자로된 아이디는 쉽게 알아 낼 수 있음.

**Comment by ajh1000** [comment]
document.getElementsByClassName('cnt-quest-scene')[0].attributes[3].value

이 코드로 닉네임 얻어오긴했는데 이런거 맞음?

**Comment by sidewinderk** [comment]
오호, 맞는듯. 땡큐.
유저이름이 없는 퀘스트에서는 이 데이터를 안가져와서 비어있었는데, 유저 이름이 들어간 퀘스트에서는 정상적으로 가져오네. 적용해서 업데이트해야겠음.
