### ISSUE TITLE
토속 나루메아 스킬 번역 중복 적용 오류

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#41]
![이미지](https://imgur.com/wxF1gD9.png)

**Comment by sidewinderk** [comment]
해결함!
원문은 아래였는데,
`<div class="prt-text-small">自分に弱点属性追撃効果/カウンター効果(回避・被ダメージ/*回)　<span class="text-blue">◆奥義ゲージを**％消費/奥義ゲージ***％消費で効果時間延長</span></div>`
번역문을 아래 처럼 누가 해둬서
`<div class="prt-text-small">자신에게 약점속성 추격 효과 / 카운터 효과(회피・받는 데미지/*회) <span class="text-blue">◆오의 게이지를 ***% 소비하여 지속시간 연장</span></div>`

문제가 발생함. 구체적으론, 오의게이지를 **%소비 / 오의게이지를 ***%소비하여, 라고 두번 나오는데 아마.. 추출할때랑 달라졌거나 그러지 않았을까?
아래로 수정함
`<div class="prt-text-small">자신에게 약점속성 추격 효과 / 카운터 효과(회피・받는 데미지/*회) <span class="text-blue">◆오의 게이지를**％소비/오의 게이지를 ***% 소비하여 지속시간 연장</span></div>`
