### ISSUE TITLE
SceneCode 없앨까 말까

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#47]
생각하다보니까 SceneCode는 의미가 없어진것같아서 같이 결정을 해야할것같음.

# 문제 원인
SceneCode를 만든 이유가 일어판과 영어판의 번역 공유를 위해 만든거였음.

정확히는 번역 적용 알고리즘때문인데  ```translate_StoryText``` 함수의 코드 중에
```
    let sc = SceneCodeFromURL();
    jsonFile.some(function (item) {
        if (String(item.SceneCode).includes(sc)) {
            sceneData.push(item);
        }
    });
```

이게 있는데 SceneCode로 하나의 그룹을 생성하고있음.

영어판 플레이하는 사람들은 questJson에서 **영어 번역문이 없을 경우** 해당 그룹에서 일본어 번역문을 **"찾아서"** 적용함.

그 "찾아서"에 해당하는 부분이

```
for (var i = 0; i < sceneData.length; i++) {
        if (!sceneData[i].Origin)
            continue;
        if (stext.length == sceneData[i].Origin.length) {
            if (stext == sceneData[i].Origin) {
                if (sceneData[i].Korean) {
                    transText = sceneData[i].Korean;

                    //튜토리얼 페이지 플레이중에는 유저 네임이 디폴트 네임으로 되있으므로 그랑 or 지타로 설정하게함.
                    if (SceneCodeFromURL().includes('tutorial')) {
                        if ((userName == 'グラン' || userName == 'Gran')) {
                            transText = transText.split(generalConfig.defaultTransNameMale).join('그랑');
                            transText = transText.split(generalConfig.defaultTransNameFemale).join('그랑');
                        } else if ((userName == 'ジータ' || userName == 'Djeeta')) {
                            transText = transText.split(generalConfig.defaultTransNameMale).join('지타');
                            transText = transText.split(generalConfig.defaultTransNameFemale).join('지타');
                        }
                        break;
                    }

                    transText = transText.split(generalConfig.defaultTransNameMale).join(userName);
                    transText = transText.split(generalConfig.defaultTransNameFemale).join(userName);
                    break;
                } else {  <=============여기 부분 ===================>
                    var offset = 0;
                    if (sceneData[i].Language == 'Japanese') {
                        offset = i - jpStartIndex;
                    } else if (sceneData[i].Language == 'English') {
                        offset = i - engStartIndex;
                    }

                    transText = sceneData[offset].Korean;
                    break;
                }
            }
        }
    }
```
이 함수의 else 부분임. 여기서부터 일본어 원문과 영어 원문의 순서는 동일하니 순서에 해당하는 offset을 찾아감.

# 해결책
어찌됐든간에 이런 복잡한 짓거리를 안해도 됨.

그냥 구글 스프레드 시트에 일어판/영어판 추출문을 평소대로 업로드하고, 번역을 할때,

일본어로 번역을 완료했으면 밑에 영어 추출문의 Korean 부분에도 복붙을 해주면 됨.

그럼 원인이였던 " questJson에서 **영어 번역문이 없을 경우** " 가 해결됨.

# 해결책 : 장점
코드가 간결해지고, 유지보수가 아주 아주 편해짐. 그냥 translate 함수처럼 간결하게 작동시켜도 될정도로.

스토리 텍스트 추출할때나 번역문 적용할때나 신경쓸게 사라져서 개발이 편해짐.

# 해결책 : 단점
자잘한 문제인데 CSV 포맷을 

Language | SceneCode | Type | Name | Origin | Korean
-- | -- | -- | -- | -- | --

에서

Type | Name | Origin | Korean
-- | -- | -- | --

으로 변경해야하니까 엑셀 작업을 해줘야함. 근데 이건 내가 하면 되니까 괜찮음.

그리고, 잠재적인 문제로 퍼포먼스에 영향이 있을려나? 근데 이건 정말 미미할것같음. 지금도 거대한 archive.csv 에서 번역문을 찾아 적용해나가는것보면 속도는 준수해보이니까 괜찮아보임.

귀찮다고 생각할수도있는 부분도 있는데, 영어판 플레이하는 사람도 번역문 적용하게 해줘야하니까 일어 추출뿐만 아니라 영어 추출도 해줘야하는 작업을 반드시 해줘야한다는 거랑, 번역 적용을 위해 일본어 번역문을 그대로 영어 번역문에 복붙해줘야한다는 가이드 라인이 추가된다는 번거로움이 늘어남.

그래서 이러한 변경점을 적용하는것은 어떻게 생각함?

**Comment by sidewinderk** [comment]
고민해봤는데,
굳이 지금 있는 추출 DB의 틀을 갈아엎을 필요까지는 없을 것 같음. 

그냥 해당부분 코드를 type/name/origin/Korean 만 쓰도록 만들어두고, 추출할 때는 여전히 SceneCode 와 Language 를 포함해서 추출하는거지.
동시에, SceneCode 정도는 번역문 검색시에 한번 필터로 쓰고, 번역문을 고르는 것도 좋을 것 같음. (이쪽이 텍스트 길이가 짧음)

왜 굳이 저 두 정보를 남겨두고자하냐면,
1. 혹시나 변경사항에 문제가 생겼을때 언제든지 롤백 할 수 있음.
2. 기존에 업로드된 추출문을 수정할 필요가 없음
3. 기존에 만들어둔 추출 튜토리얼 영상을 새로 찍을 필요가 없음
4. (부가적으로) 번역문 정리해둔 웹사이트(gbf.maru.moe)에서 SceneCode와 Language 정보를 사용함.

어떻게 생각함?

**Comment by ajh1000** [comment]
오 알겠음 

님이 말한대로 번역 적용할때는 기존처럼 SceneCode로 필터를 먼저 걸어보고, 

SceneCode 가 없으면 Json 파일의 처음부터 끝까지 Origin을 찾아가며 번역해나가는 방식이 좋아보임.

사실 신코드 추출은 이제 완벽하게 할수있는데 번역 적용을 하는 부분에 난관이있었음. 근데 이제 이렇게하면 나중에 방법이 떠올랐을때도 편하긴하겠네. 

ㅇㅋ! 감사감사

**Comment by ajh1000** [comment]
gbf.maru.moe 홈페이지는 혹시 오픈 소스임? 

홈페이지 지금 보다보니 배경 이미지랑 캐릭터 이미지 추가하는것도 가능해보여서 나중에 코드 기여해보고싶음.

**Comment by sidewinderk** [comment]
이 사이트는 오픈소스임. 
https://github.com/gbfkor/gbfkor.github.io
여기에 올려뒀는데, 현재 자동 생성방식으론 텍스트 데이터만 읽히게 되어있음.
차후에 기여자가 늘면 imgur 등에 일러스트를 업로드해두고 그 주소를 번역DB 사이에 특수기호 등을 활용해서 넣어둔 다음,
포스트를 만들 때 삽입한다거나 하는 방식의 활용으로 고려해보고있었음.

**Comment by sidewinderk** [comment]
대충 GitHub Action기능을 활용해서, 
gbfTransKor 에 새 commit 이 Push 되면 아래 링크의 Ping-Pong 이라는 작업을 돌려서 gbfkor 에 알려주고,
https://github.com/sidewinderk/gbfTransKor/runs/1584453432?check_suite_focus=true

gbfkor에서는 ping 을 받으면 해당 repository 의 업데이트를 반영해서 사이트를 업데이트하는 방식임
https://github.com/gbfkor/gbfkor.github.io/runs/1584453820?check_suite_focus=true

**Comment by sidewinderk** [comment]
SceneCode 문제는 해결된 듯함. 닫겠음.

**Comment by sidewinderk** [comment]
이번 제야의 끝에서 울리는 종 이벤트 스토리 추출 중에 확인한 건데, SceneCode 가 정상적으로 추출되지 않는듯함.

프롤로그에선 정상적으로 추출이됐는데, 1-1화 이후로 코드와 스토리 텍스트가 정상적으로 추출되지 않음.
확인해 줄 수 있음?

**Comment by ajh1000** [comment]
혹시 루리아 노트에서 추출했음? 아니면 이벤트 플레이 페이지에서 추출했음? 

지금 거의다 고치긴했는데 고치기 이전 코드로 돌려봤을땐 루리아 노트에서는 잘 뽑혔음.

**Comment by sidewinderk** [comment]
제야의 끝에서 울리는 종 이벤트 추출은 이벤트페이지에서 진행함.

추가로, 여기저기서 SceneCode를 제대로 추출 못하는 문제가 발생하는듯함.

예를들면 슈트름 페이트 에피소드를 루리아노트에서 추출시도하면 SceneCode 를 못 긁어옴.

![Screenshot 2021-01-24 at 12 00 47](https://user-images.githubusercontent.com/29934369/105628198-cff5b580-5e3b-11eb-9a20-845527804396.png)

--
비슷하게 죠이 신뢰도 이벤트(이벤트 다 깨고 배틀 깨다보면 나오는)에서는 SceneCode는 잘 추출하지만 주인공 이름을 치환하지 못하는 문제가 있는듯함.

**Comment by sidewinderk** [comment]
코드 관련 문제는 해결된 것으로 보임. 하지만 여전히 일부 퀘스트에서 유저이름 치환이 작동하지 않는듯함.
지금 추출 중인 곳은 이벤트 캐릭터 신뢰도 퀘스트임.

![Screenshot 2021-01-24 at 13 59 39](https://user-images.githubusercontent.com/29934369/105631018-8792c380-5e4c-11eb-83b6-0a67f588aeb3.png)

**Comment by sidewinderk** [comment]
...? 또 맞게 나옴.. 확장툴 업데이트가 잘 안됐었나? 

![Screenshot 2021-01-24 at 14 26 43](https://user-images.githubusercontent.com/29934369/105631743-44d2ea80-5e50-11eb-8689-50e6e464c43d.png)


일단 해결된걸로 보고, 계속 추출중인데, 재발하면 다시 열겠음.

**Comment by ajh1000** [comment]
이게 좀 신기한게 캐시 지우기해서 새로고침 하면 다시 정상 작동하는 느낌이있음.

정확한건 다시 코드 봐야겠는데 암튼 ㅇㅋ!
