### ISSUE TITLE
홍보 문구에 대해

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#49]
최근 갤에 올라온 글 잘 읽었음.  [링크](https://gall.dcinside.com/board/view/?id=granblue&no=3372441)

글 읽고 내가 느낀게,

안전성에 대한 믿음의 확산속에서 만일의 사태가 벌어지면 사람들이 엄청 기분이 상할태니까 그것을 조금 완화하기 위한 홍보 문구 추가에 대해서 글을 써봄.

비라메이트도 3년인가 지나서 밴당했다고 알고있는데 번역툴의 밴 위험도 조금 불안하긴함. 물론 비라메이트 밴 원인은 사용자가 스킬 시전을 원래 스킬 시전해야할 페이지에서 하지않고 엉뚱한데서 시전하는 비정상적인 클릭이 원인인것같긴함. 우리는 모든 원칙은 잘 지키고있지만 혹시 모르는거니까. 그리고, 레딧을 계속 뒤져보고있긴한데 자기가 만든 폰트 스타일 변경 스크립트를 아직까지 잘 사용하고있다는 사람들도 보이고, ublock origin 같은 광고 차단 프로그램을 써도 밴 안당하는거보면 게임사가 크게 신경쓰는건 아닌가 싶기도함.

아무튼, 번역툴 사용 대상을 명확히 알려줘서 밴 위험성을 계속 강조하면 만일의 사태가 벌어졌을때 마음이 조금은 더 편할듯.

밑에는 내가 생각해본 사용 대상 글임.

**밴 당할 수도 있으니까 이런 사람들만 사용하길 바람**
1. 부계정 생성해서 번역툴을 즐겨볼 사람. 
2. 게임 처음 시작해서 게임 방식을 익혀볼 사람. 
2. 밴 당해도 상관 없는 사람.
3. 곧 접을 사람.

최대한 밴 안당하게끔 안전한 방면으로 번역툴을 만들긴 했지만 혹시 모르니까 사용하기 애매한 사람은 사용하지 않는걸 추천한다고 강조.

툴 사용자 중에 밴이 너무 걱정인 사람은 이미지 번역&전투 화면 번역 기능은 사용하지말고 번역하기 기능만 사용하라고 강조하기.

그리고, 영어나 일본어를 조금이라도해서 게임 플레이에 지장이 없는 사람들은 번역툴 없이  게임하라고 강조하는것도 어떨까싶음.

스토리는 여기 [gbf.maru.moe](http://gbf.maru.moe) 에서 보라고 하면 되고.

마지막으로, 밴 당한다해도 [gbf.maru.moe](http://gbf.maru.moe) 여기서 번역이 계속 이루어지니까 프로젝트는 멈추지 않을거라고 까지 말하면 좋을것같음.

어떻게 생각함?

**Comment by sidewinderk** [comment]
먼저 미안한게, 내가 정확히 말하는 의도를 파악하고 있는지 잘 모르겠음. (잘못이해한거면 정정바람)

> 안전성에 대한 믿음의 확산속에서 만일의 사태가 벌어지면 사람들이 엄청 기분이 상할태니까 그것을 조금 완화하기 위한 홍보 문구 추가에 대해서 글을 써봄.

이 말은 모든 글/번역 툴에 적혀있는 아래 문구(Disclaimer)를 보완하자는 의미 맞지?

> 이 번역 툴이 운영국의 '외부툴 사용에 따른 밴' 정책에 대해 안전하다고 보장해줄 수 없음.
> 각자 판단 하에 사용할 것

이 문구를 수정한다는건 크게봐서 두가지 방향성이 있을 수 있는데,
1. 경고문의 수위를 높여서, 만약의 사태에 대비되지 않은 피해자를 줄인다.
2. 경고문의 수위를 낮춰서, 더 많은 유저/번역자 들이 참여하도록 한다.
라고 생각함.

툴 사용이 굉장히 그레이존에 가깝다고 생각해서 기존의 문구에선 불의의 사태가 있을 수 있다는 점과 사용자의 책임을 강조하여, 최대한 건조하게 표현하고자 했음.

그런데 제안 한 수정 방향은 
1. 사용 유저 층을 구분하여 책임소재를 더 명확히 하자. (경고문의 수위를 높이는 효과)
2. 이미지/전투화면 번역 등에 대한 옵션 유무를 좀 더 강조하여 유저들의 불안을 덜자 (경고문의 수위를 낮추는 효과)
3. gbf.maru.moe 의 존재를 좀 더 홍보해서 번역자들의 의욕을 고취하자 (경고문의 수위를 낮추는 효과)
이렇게 이해했는데, 내가 보기엔 의도가 혼재되어있는 것으로 보임.

만약 좀 더 우리의 책임을 덜고자 한다면, 경고문을 좀 더 강하게 보충하는 방향이 맞을 것 같고,
좀 더 참여하는 유저/번역가를 늘리고자 한다면 좀 더 간결한 문장을 쓰는게 좋을 듯함.

정확히 어떤 방향을 원하는 것임?

**Comment by ajh1000** [comment]
이번 PR #50 을 하면서 생각이 바뀜.

이전 PR까지는 밴 안당할려고 소극적인 자세로 개발했는데 이번 PR부터는 과감하게 기능들을 구현하다보니까 밴에 대해선 더이상 신경안쓰기로했음.

앞으로는 번역 속도를 높이기위한 방향으로 갔으면 좋겠음.

경고 문구는 바꿀 필요 없어보임.

3번의 gbf.maru.moe의 존재만 어필해서 밴 당해도 이 프로젝트는 끝나지 않는다를 알리면 좋을것같음.

그리고, 번역툴 개발이 내 생각엔 이제 끝난것처럼 보여서 튜토리얼 페이지 부터 순서대로 쭉쭉 번역해나가면 좋겠다고 생각함.

그래서 앞으로는 번역자들이랑 같이 소통하면서 번역을 어떻게 할지에 대해서만 신경써보는건 어떨까싶음.

**Comment by sidewinderk** [comment]
오케이, 일단 남은 자잘한 부분을 마무리하고, 조만간에 새로 글을 쓰겠음.
개발쪽 손은 좀 줄이고 번역쪽에 힘주는 방향으로.. 

이 이슈는 닫아두겠음.
