### ISSUE TITLE
게임 진행중 번역 기능이 해제되는 현상

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#5]
말 그대로, 게임을 진행하다보면 번역 기능이 풀려있는 현상이 발생함.

쉽게 재현해보는 방법으로는, 아무 전투퀘스트(엑스트라/멀티)나 들어가서 클리어 하면, 퀘스트 보상 페이지부터 번역이 일부 풀려있는 것을 확인할 수 있음.
(사실 그냥 게임 하다보면 심심찮게 발생함)
이는 새로고침을 한번 해줌으로서 해결이 가능하지만, 좀 더 근본적인 해결책이 있으면 좋을 것 같음.

**Comment by ajh1000** [comment]
```

async function ObserverArchive() {
	// var oText = document.getElementById('loading');
	var oText = document.getElementById('wrapper');
	if (!oText) {
		//The node we need does not exist yet.
		//Wait 500ms and try again
		window.setTimeout(ObserverArchive, generalConfig.refreshRate);
		return;
	}
	if (
		document.URL.includes('raid') // Do we need this?
	)
		return;
	else archiveObserver.observe(oText, config);

	//journal 페이지에서 스토리 재생할 때 다음 scene으로 넘어가면,
	//observer 가 disconnect됨. 이유는 모르겠음. 그래서 로딩 중일때 다시 연결하도록함.
	if (document.getElementById('loading').style.display == 'block') {
		ObserverPop();
		ObserveSceneText();
		ObserverEventChapterList();
	}
	
	
}

```

아마 내가 경험했던거랑 비슷한거같은데. loading 창이 뜰때 바로 observer들이 해제되던데 나는 로딩창 뜰때 다시 연결해주는걸로 해결했음.

**Comment by sidewinderk** [comment]
흠.. 단서 감사.
일단 테스트를 해보겠음.
만약 같은 문제라면, 따로 document.getElementById('loading').style.display 만을 감시하는 옵저버를 만들어서, 해당 DOM이 block일 때 모든 옵저버를 켜주는 기능을 넣어줘야할듯.

**Comment by sidewinderk** [comment]
제안된 방법으로는 해결이 되지 않았음.

극단적인 방법으로,
var LoaderObserver = new MutationObserver(function(mutations) {
    LoaderObserver.disconnect();
    console.log("시작!");
    main();
    ObserverPageLoader();
});
async function ObserverPageLoader() {
    var oText = document.getElementById('loading');
    if (!oText.style) {
        //The node we need does not exist yet.
        //Wait 500ms and try again
        window.setTimeout(ObserverPageLoader, generalConfig.refreshRate);
        return;
    }

    LoaderObserver.observe(oText, config);
}

이렇게 loading DOM이 바뀔 때 마다 main을 다시 불러오는 방법을 시도도 해봤는데, 스크립트가 굉장히 느려지고, 번역 DB를 다시 불러오지 않으면 텍스트 번역을 안하는 문제가 여전히 있음.

좀 더 파볼 예정.

**Comment by ajh1000** [comment]
```
async function ObserverArchive() {
	// var oText = document.getElementById('loading');
	var oText = document.getElementById('wrapper');
	if (!oText) {
		//The node we need does not exist yet.
		//Wait 500ms and try again
		window.setTimeout(ObserverArchive, generalConfig.refreshRate);
		return;
	}
	/*
	if (
		document.URL.includes('raid') // Do we need this?
	)
		return;*/
	else archiveObserver.observe(oText, config);

	//journal 페이지에서 스토리 재생할 때 다음 scene으로 넘어가면,
	//observer 가 disconnect됨. 이유는 모르겠음. 그래서 로딩 중일때 다시 연결하도록함.
	if (document.getElementById('loading').style.display == 'block') {
		ObserverPop();
		ObserveSceneText();
	}
}```

원래 ObserverArchive 코드에서 두번째 if문을 주석처리하니까 정상 작동함.

**Comment by sidewinderk** [comment]
주석 제거를 해줘도 여전히 전투 퀘스트 종료후 번역이 풀리는 문제가 있음.

번역이 풀릴 때는 이러함: https://youtu.be/kyl3nVf8RoI
번역이 안풀리는 경우(위의 ObserverPageLoader 를 썼을 때): https://youtu.be/EuO4ewMvWns

**Comment by ajh1000** [comment]
전투 결과창에 보이는 텍스트들. 획득 경험치, 엑스트라 배틀로 이런 글자들은 csv 파일중에 어디에 입력되어있음? 난 이런 텍스트들 안보여서 archive.csv에 넣고 똑같이 해봤는데 번역 안풀림. 한번 내 코드로 해보시는게어떰. 아 그리고 주석을 제거하라는게 아니라 주석으로 저 if문을 감싸라는거였음. 

 [다운로드](https://github.com/ajh1000/gbfTransKor/archive/master.zip)

**Comment by sidewinderk** [comment]
아, 해당 텍스트는 내가 테스트용으로 추가한 텍스트임(전투 결과창에서만 보이는 텍스트)
오케이. 해결되는걸 확인했음.

다만, 지금 전투 페이지에서의 번역을 옵션으로 빼두려고 BattleObserver를 따로 만든거라서, raid url에 대한 if문은 필요함.
좀 더 파보니, url이 맞지 않으면 그냥 return을 해버리는게 문제였음.

if (document.URL.includes('raid')) {
        window.setTimeout(ObserverArchive, generalConfig.refreshRate);
        return;
}
archiveObserver.observe(oText, config);

이런식으로 각 observer 들의 url 체크 시에, timeout으로 다시 해당 옵저버를 기동하는 과정을 넣어서 해결햇음.
이러면 아래의 ObserverArchive 아래의 if (document.getElementById('loading').style.display == 'block') 문이 없어도되므로 삭제함.

**Comment by ajh1000** [comment]
아 ㅇㅋ 이해함

**Comment by sidewinderk** [comment]
해결되었으니 닫겠음.
