### ISSUE TITLE
번역툴에서 추출되지 않는 영역 보완 #1

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#53]
몇군데 번역툴에서 추출/번역해내지 못하는 영역이 있음.
모두 같은 필드인지는 모르겠으나, 일단 아래 제보 받은 부분은 주로 아이템 교환 리스트와 재고 등이 해당됨:

https://docs.google.com/spreadsheets/d/1LQiu94RhA5gRlcOja0oMrtRKfql14yCvJZlpa25xvi0/edit?disco=AAAAHOQbpXI

개발/디버깅용으로 테스트 할 때는 상점-트레저교환 에 있는 교환목록이 같은 인터페이스인 듯하여, 참고로 하면 좋을듯.

**Comment by ajh1000** [comment]
아하 확인해보겠음

**Comment by sidewinderk** [comment]
아이템 교환 리스트 페이지 번역 적용 된 것 확인했음. 닫아두겠음.
