### ISSUE TITLE
이벤트 배너가 정상적으로 출력되지 않는 문제

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#56]
![Screenshot 2021-01-23 at 16 20 51](https://user-images.githubusercontent.com/29934369/105608061-05e65b80-5da2-11eb-87e2-16e5cd229836.png)

이벤트 베너를 가져올 때 통신상 문제가 발생하는지, 정상적으로 표시되지 않고 붕 뜨는 문제가 있음.

**Comment by ajh1000** [comment]
으음

일단 난 지금 이미지 업데이트하고 다시 들가봤는데 정상적으로 뜸. 무슨 문제일까. 일단 짚이는 부분이있는데 그 부분을 수정해보겠음.

**Comment by sidewinderk** [comment]
이게 항상 그런건 아니고, PC기준으로 종종 일어나는듯함.

**Comment by sidewinderk** [comment]
일단 재발하지는 않고 있음.
해당 이벤트 배너가 gif같은식으로 움직이는 형태여서 그랬을 거 같은데, 재발하면 다시 열어보겠음.
