### ISSUE TITLE
번역 오류들

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#57]
1. 튜토리얼 전투 화면 공격 버튼 이미지 깨짐
![2](https://user-images.githubusercontent.com/22585023/105621717-e7d63500-5e4d-11eb-9f6e-7073678be108.PNG)

2. 튜토리얼 페이지에서 유저네임 치환 안되는 부분.
![3](https://user-images.githubusercontent.com/22585023/105621728-ff152280-5e4d-11eb-9203-b694cf4860f9.PNG)

나머지 이슈들도 확인하고 고치겠음.

**Comment by sidewinderk** [comment]
공격버튼은 바꾸고 튜토리얼을 안해봐서 발견을 못했네, 추가로 작업해두겠음.

**Comment by sidewinderk** [comment]
![Screenshot 2021-01-24 at 08 08 09](https://user-images.githubusercontent.com/29934369/105623625-754c6180-5e1b-11eb-89c6-835547002757.png)

튜토리얼 쪽은 일단 추가 되었음.
