### ISSUE TITLE
전투 텍스트 유저명 치환

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#59]
![Screenshot 2021-01-24 at 22 20 05](https://user-images.githubusercontent.com/29934369/105643823-78ceff80-5e92-11eb-9661-aa075c3247a4.png)

전투 텍스트에서 유저명 치환이 생략된 것 같음.

**Comment by ajh1000** [comment]
오우 이거 관련해서 생각해봤는데 추출한 유저네임을 전부 [グラン] 으로만 바꾸는건 어떻게 생각함?

기존에는 성별에 따라, 영어판인지 일어판인지에 따라 
```
defaultNameMale_jp: "[グラン]", // Default original user name
    defaultNameFemale_jp: "[ジータ]",
    defaultNameMale_en: "[Gran]",
    defaultNameFemale_en: "[Djeeta]",
    defaultTransNameMale: "[그랑]", // Default translated user name
    defaultTransNameFemale: "[지타]",
```
이렇게 나눴었는데, 이것을  [グラン] 이걸로만 추출하거나 [플레이어] 라고 추출하게하거나 단일화를 하는건 어떻게 생각하는지 알고싶음.

단일화를 하고 싶은 이유는 개발의 편의성이 주된 이유임.

**Comment by sidewinderk** [comment]
원래 의도는, 추출된 텍스트에 성별에 따라 다른 표현(그/그녀)이 있으면 거기 맞춰서 대응해주기 위함이었는데,
성별에 따라 다른 텍스트가 있으면 맞춰서 추가로 추출이 될 것으로 기대하므로 단일화해도 될 것 같음.

**Comment by ajh1000** [comment]
알겠음. 

우리 구글 스프레드 시트에 [ジータ]이나 [グラン]으로 되어있는 부분들은 내가 컨트롤+F 키를 써서 [플레이어]로 모두 바꾸기 하겠음.

바꾸는 시기는 다음 PR이 승인됐을때 바꾸도록하겠음.

근데 두 번째 줄에 쓴 말을 내가 살짝 이해못해서 정말 미안한데 혹시 어떤 뜻인지 다시 말해줄수있음?ㅠ
```성별에 따라 다른 텍스트가 있으면 맞춰서 추가로 추출이 될 것으로 기대하므로 단일화해도 될 것 같음.```

혹시 예를 들어서 말해줄수있으면 좋을거같음. 이 부분에서 내가 잘못 이해하고 넘어가면 나중에 문제 일어날것같아서 ㅎㅎ ㅠ

**Comment by sidewinderk** [comment]
아 저 부분은, 원문에서 성별에 따라 다른 문장을 쓴다면.. 예를들면 주인공을 '그'라고 표현한 문장이 있고 '그녀'라고 표현한 문장이 각각 따로있으면 아마 서버에서부터 성별에 따라 문장을 다르게 입력해뒀을것으로 생각되므로(선택지에 따른 대사가 여럿있듯이) 추출될 때 성별에 대한 문장이 각각 따로 추출될것으로 기대한다는 뜻이었음.

**Comment by ajh1000** [comment]
Japanese | scene_tutorial00,011 | synopsis |   | 父親の残した手紙に導かれ、空の果てへと旅立とうとする少女。しかし、時を同じくして村には戦艦が現れ、謎の少女が助けを求めてくる。 | 아버지가 남긴 편지에 이끌려, 하늘의 끝으로 여행을 떠나려던 소년(소녀). 하지만, 동시에 마을에는 전함이 나타나고, 수수께끼의 소녀가 도움을 청해온다.
-- | -- | -- | -- | -- | --




아하 이해함.

위의 예문이 바로 그 경우인데 계정 생성하고 지타로 했을때 처음뜨는 스토리 줄거리 문장임.

저기서는 지타로 시작했으니까 서버에서는 성별을 여자로 인식하고 少女로 문장을 조립했을듯.

완전히 추출할려면 그랑, 지타로 번갈아가며 플레이하며 추출해야되는 불편함이 있음.

물론 그냥 추출해서 구글 스프레드 시트에서 수동으로 한 줄을 직접 추가해서 少女를 소년으로 수정해도됨.

어쩌면 님 말대로 성별 지칭만 바뀌는게 아니라 문장 내용 자체가 바뀔 수도 있을것같음.

아무튼 그런 부분들은 현재로서는 수동으로 지타에서 그랑으로 바꿔가며 추출하는 방법밖에 안떠오름. 

욕심부려서 성별에 따른 완벽한 추출 방법을 생각해봤는데  아무래도 지타로 플레이하면서 그랑으로 플레이했을때의 문장까지 한꺼번에 추출해보는건 힘들듯.

혹시 내가 제대로 이해한거 맞음?

**Comment by sidewinderk** [comment]
이해한게 맞음. 
근데 저 성별에 따른 문장이 한번에 둘 다 추출될거라고 생각했는데, 적어도 튜토리얼은 같은 코드로 성별을 고정해서 나오는 듯 하니 좀 곤란한듯도..

**Comment by sidewinderk** [comment]
새 PR로 적용됨. 닫아두겠음.
