### ISSUE TITLE
텍스트 추출&번역 적용 완벽하게 하는 법

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#6]
1. 아무거나 스토리 하나 플레이한다.
2. F12눌러서 크롬 devtool 키고, network 탭으로간다.
3. 바로 아무거나 항목 오른쪽 마우스 눌러서 save all as HAR content를 누른다.
4. har-extractor라는 npm module 프로그램으로 저장한 har을 추출한다.
5. 추출한 결과물중에 scene_list를 담고있는 json파일이있다. 이놈을 조진다. 

지금 시간 없어서 일단 이미지만 올리고 나머지는 내일 해보겠음. 이게 잘 된다면좋겠는데.
![1](https://i.imgur.com/4bwcGIF.png)
![2](https://i.imgur.com/E90uEPy.png)
![3](https://imgur.com/ZvWJSuf.png)
![4](https://imgur.com/wMTiVQe.png)
![5](https://imgur.com/DyRyOU9.png)

**Comment by sidewinderk** [comment]
오호 이게 되면, 굳이 하나씩 읽어가며 기다릴 필요 없이 한번에 퀘스트 추출이 가능하다는거지? 기대하고있겠음.

**Comment by ajh1000** [comment]
![1](https://imgur.com/wvTZtNe.png)

chrome.devtools.network API를 활용함. 개발자도구 - network 탭에 출력된 결과물들을 대상으로 분석할수있게해주는 API. 

devtools.js, devtools.html을 폴더에 추가해서 만들어야되고 menifest.json 파일에는 
```"devtools_page": "devtools.html"```   을 추가해야됨.

sceneCode를 성공적으로 알맞게 뽑았고, 스토리에서 재생되는 모든 텍스트들(선택지, 줄거리...) 성공적으로 변수에 담음. 이제 번역 적용하는 코드 짜면 될것같음.

devtools.js 다루는법 공부하느라 시간이 엄청 흘렀는데 적어도 다음주 주말까지는 스토리 번역 기능은 완성될것같음. 만들면서 피드백하겠음.

**Comment by sidewinderk** [comment]
계속 개발하는 것도 좋은데, 잠시 방향성을 한번 돌아보자.

내가 생각하는 스토리 텍스트 추출법은
기본적으로 누구나 번역툴 이외의 추가적인 툴 설치 없이 게임을 진행하면서 자연스럽게 쌓이는 데이터를 기여하고 번역하는데 있음. 그래야 누구나 본인이 그냥 게임하다가 얻게 된 번역이 되지 않은 텍스트를 부담없이 스프레드 시트에 올리고 번역을 요청하거나, 본인이 번역을 진행해볼 수 있으므로.

만약 이 방법이 기존 번역툴에 내장되어, 퀘스트 들어가서 바로 추출버튼을 누르면 원하는 포멧으로 정리해서 원문을 내주는 방법으로 개발이 가능하면 이 쪽을 새로운 텍스트 추출의 베이스라인으로 삼는 방향으로 개발하는게 좋을 것 같고,
만약 이 방법이 기존 번역툴에 내장이 불가능하고, 추가적인 소프트를 설치해야하면서 접근성이 떨어지는(추출방법으 따로 배워야하는) 방법으로만 사용할 수 있다면, 옵션으로 두고 진행하는게 좋을듯.

어떻게 생각함?

**Comment by ajh1000** [comment]
오 나도 확장 프로그램에 들어가서 추출버튼 누르면 바로 csv 파일로 뽑아주게 할려고 생각함. 번역자들 친화적으로. 어렵지않게. 

그래서 처음에는 소프트를 설치해서 텍스트를 추출하는 방법을 생각했지만 그건 아닌것같아서 확장프로그램에 기능을 내장할수있는 방법으로 돌아감. 

결국 기능을 내장하는데에 성공했으니까 거시기를 베이스라인으로 삼는 방향으로 가는게 좋겠다.

**Comment by sidewinderk** [comment]
오케이.

일단 내가 지난번 스토리 번역문 업데이트 버전까지를 업데이트해서 git에 올려둘테니 그걸 기준으로 다시 작업해주면 좋겠음. (번역스크립트가 멈추는 문제와 번역문에 유저이름 있으면 치환하는 내용이 추가됨) 
그리고 기능이 추가되면(기존 기능과 상충하지 않을때는) 가능하면 pull-reqeust를 해서 누가 어떤 부분을 수정했었는지 기록에 남도록 작업해주면 좋겠음. 지금까지는 내가 보고 복붙해서 올렸는데, 본인이 작업한거기도 하니까 기록에 남겨두는게 맞겠지.

**Comment by ajh1000** [comment]
알겠슴. 풀리퀘스트하기 무서웠떤게 괜히 했다가 버그 생겨서 뭐가 안되고 하는게 무서웠는데 이제는 어느정도 괜찮아졌으니까 다음 커밋때는 풀리퀘스트 하겠음.

**Comment by sidewinderk** [comment]
좀 더 안전하게 진행하려면 dev 버전으로 branch를 새로 파서 진행해도됨.

**Comment by ajh1000** [comment]
음 그거 좋네. 그럼 님이 dev 브랜치 만들고 거기다가 내가 풀리퀘스트를 신청하는식으로 하면 될려나?

**Comment by sidewinderk** [comment]
본인이 dev 브랜치 만들고 pull 신청을 해도 아마 될 것임.

**Comment by ajh1000** [comment]
ㅇㅋ 그렇게하겠음.

**Comment by ajh1000** [comment]
이번 일주일동안 여러가지로 시도해봤는데 상황이 안좋아서 중간 보고할려고 함. 3줄 요약은 맨 밑에 있음.

devtools.js 안에다가 chrome.devtools.network API를 호출하고 테스트해봤을때 모든 텍스트(분기문, 선택지, 줄거리) 들을 추출하는데 성공함. 문제는 번역 적용할려고보니까 선택지, 줄거리는 모두 적용이됐는데 분기문은 적용이 안됨. 이건 정말 당연한 부분이였는데.. 

어떤 플레이어가 어떤 캐릭터를 가지고있는지는 루리아노트를 통해서 스토리를 플레이한다면 URL을 기준으로 구분이 가능함. 

예를들어, 최근 십천중 이벤트인 Seeds Of Redemption 에서 1챕터 2 에피소드를 플레이하면 나루메아를 가지고있다고 체크박스에 체크할경우 URL은 play_view_event/75180/75181/null/2/1/3/3040249000 이렇게 됨.

그럼 맨 뒤의 숫자 3040249000 이 부분이 나루메아에 해당하는 코드라서 현재 스토리 재생하고있는 플레이어가 나루메아 가지고있다는 구분이 가능해짐. 문제는 루리아노트가아닌 이벤트 플레이 페이지에서 스토리를 재생하는 사람들 대상으로는 URL 구분이 불가능함. 왜냐면 URL에 구분 가능한 어떠한 표시도 안드러남. 

기쁜 소식은 F12눌러서 network로 봤을때 받아오는 scene_list JSON 파일을 보면, 캐릭터를 가지고있을때는 character_flag가 1로 표시되고 없으면 0으로 표시됨. 

다시 나쁜 소식은 F12눌러서 나오는 network 결과값들을 받아오는 API는 핸드폰에선 호출이 안됨. F12를 눌러서 개발자 도구를 띄워놔야지만 해당 API를 호출할수있음. 핸드폰에서는 개발자 도구(F12)를 못 키니까 ... 더불어 사람들보고 매번 F12눌러야지만 번역 적용됩니다~ 라고 말할수도없는 부분이고.

#### 그러므로, network 결과값들을 받아오는 다른 API들을 찾아보기로함. 

#### 3줄 요약
1. 모든 텍스트 추출 성공(분기문, 선택지, 줄거리). 하지만 번역 적용 실패.(분기문)

2. 플레이어가 어떤 캐릭터를 가지고있으면 어떤 분기문을 적용할지 고민하다가 서버에서 받아온 scene_list JSON 파일에 어떤 캐릭터를 가지고있는지 정보가 들어있는걸 발견함.

3. 이제 서버에서 받아온 response 값들을 분석할 API를 찾고있음. 컴퓨터, 핸드폰에 모두 적용 가능한 방법을 찾고있음. 지금 도전중인것은 UserScript. 


게임 서버에다가 request를 날리는 짓은 왠지 무서워서 하기 싫고, 그냥 단말기에 받아온 네트워크 정보들을 분석할수있는 방법들을 생각해보기로함.

**Comment by ajh1000** [comment]
오케이. 방법 떠오름. 이걸로 해결가능함. 

지금 개발 완료된 텍스트 추출 기능이랑 초기의 번역 기능인 게임에서 추출한 텍스트와 quest.csv의 원문과 비교하여 번역 적용하는 기능 두 개를 합쳐서 번역 프로그램 완성할수있음.

지금은 내가 24시간 근무라 내일 오전 8시에 퇴근하는데 오전 9시부터 개발 시작해서 내일이나 월요일 중으로 완전 마치겠음.

앞으로 번역 방식은 이렇게 될것같음.

[번역자들 기여 방법]
#### 추출 방법 
1. 확장 프로그램의 번역모드를 키기
2. 스토리 진행 후 skip버튼 막 눌러서 텍스트 추출하기
3. 만약 일본어 판으로 추출했으면 이번에는 영어판으로 추출하기
4. 이렇게하고 download csv 버튼 누르기. 끝

#### 번역 방법
1. 출력된 csv 파일에서 원문 오른쪽 칸에 번역하기
2. 만약 번역자가 일어판으로 번역했다면 원문 오른쪽칸에 번역 완료한 문장들을 추출된 영어판에도 번역칸에 똑같이 붙여넣기. 끝.


ㅇㅋ 이렇게하고 지금은 짬내서 이렇게 글쓰는거라 나머지는 내일 오전 9시에 다시 오겠음

**Comment by sidewinderk** [comment]
알겠음.
한가지 문제는, 내가 이번주에 일할 때 쓰던 맥북이 죽어서 수리를 보낸터라 당장 쓸 수 있는 개발 머신이 없음.
고로 테스트를 하고 머지를 할 수 없는 상황이라, 풀리퀘스트 승인이 늦어질 수 있음.
양해바람!

**Comment by ajh1000** [comment]
오키 알겠음!

**Comment by sidewinderk** [comment]
새 버전이 잘작동하는 것 같아서 이슈를 닫으려고했는데, 생각해보니 새 추출방법에는 유저 이름이 들어간 부분에 대한 후처리가 안되어있는 것 같음.

기존의 추출방법에선, sceneObserver에서 아래와같이 
if (userName == '' && document.getElementsByClassName('cnt-quest-scene')[0]) {
    userName = document.getElementsByClassName('cnt-quest-scene')[0].attributes[3]
        .value;
}
if (userName != '') {
    textName = textName.replace(userName, generalConfig.deafultName);
    textmessage = textmessage.replace(userName, generalConfig.deafultName);
}
텍스트 안에서 발견한 userName을 generalConfig.deafultName 으로 바꾸는 방법으로 일괄 처리하고있었는데 새 방법에서는 텍스트를 devtools 에서 받아온 다음, popup으로 넘기기전에 처리를 해주던가해야할듯.

**Comment by ajh1000** [comment]
ㅇㅋ 확인함. 내일 내가 드뎌 반년만에 휴가라서 집에 오후 넘어서 도착함. 내일 중으로 해결해보겠음. 지금 바로 해결할수있으면 좋겠는데 해보고 안되면 내일.

**Comment by ajh1000** [comment]
지금 content.js 에서 253번째 줄을 보면
``` sceneJson.Name = item.charcter1_name != 'null' ? item.charcter1_name : '';```

이렇게 되있는걸 

``` sceneJson.Name = item.charcter1_name != 'null' ? item.charcter1_name : generalConfig.deafultName;```

이렇게 바꿔주면 userName이 없을때는 general.Config.deafultName 이 csv 파일에 찍혀서 출력되겠네. 

아 그리고 deafultName 이거 변수명이 오타있네. defaultName으로 수정 부탁함. 

혹시 내가 말하고있는게 원하는바가 맞음?

**Comment by sidewinderk** [comment]
일부는 맞고 일부는 아님.
해당 Json에서의 Name은 대화창에서 나오는 '이름항목'인 것 같은데, 
그 외에도 본문 텍스트나 선택지 텍스트 중에 유저명이 들어간 장면들이 가끔있음.
이걸 해결해주려면, 내 생각엔 300번째 줄에서 userName이 들어가 있으면 replace 해주는 식으로 해결할 수 있을 거 같음.

**Comment by ajh1000** [comment]
아하. 지금은 컴퓨터 사용 시간이 종료 직전이라 내일 해보겠음 오키!

**Comment by sidewinderk** [comment]
마지막 커밋으로 이 항목은 완전히 해결된 것으로 이해했는데 맞을까?
맞다면 Close 해도 괜찮을듯.

**Comment by ajh1000** [comment]
스토리 관련 텍스트들은 모두 추출 성공했고 적용되는것도 확인했으니까 닫아도 될듯. 

이제 추출하는법, 적용하는법 가이드 영상을 만들면 되겠음. 영상은 내가 함 만들어보고, 여기 이슈에 영상 링크 달겠음. 이슈는 지금 닫아도됨.
