### ISSUE TITLE
번역 속도 이슈

### ISSUE THREAD

**Issue by ajh1000** [sidewinderk/gbfTransKor#60]
마이 페이지 번역 속도가 요번 PR로 다시 느려진것같음.

개발자도구의 퍼포먼스 탭에서 테스트해보니 3초~4초 길어진듯.

그래서 이번 성능 이슈를 고쳐보고자 캐시 과정을 생각해봤음.

```gettranslatedtext``` 함수를 거쳐서 번역되고나면 ```cacheTranslatedNodes``` 라는 배열 변수에 ```{className, orig, kr}``` 객체를 추가하도록 할거임.

그렇게 완성된 배열은 ```archiveObserver`` 에서 뮤테이션이 감지될때 먼저 배열을 탐색하고 종료하도록 만들어보겠음.

그리고 그 배열은 DB에도 등록하게하면 될듯함. 다음 PR때 추가해보겠음.

**Comment by ajh1000** [comment]
신기하네.

PC 에서 탬퍼몽키 버전을 테스트하고있는데 상당히 느려서 질문하고싶음.

깃허브 메인페이지에 있는 탬퍼몽키 스크립트 링크를 따라 들어가서 설치하면 정상적인 속도로 번역이 됨.

문제는 깃허브에 올라와있는 똑같은 gbfTrans.js 를 그대로 복사해서 붙여넣기하고 돌리면 번역 속도가 진짜 엄청 늘어남.

퀘스트 - 아무거나 레이드 클릭 - 서포터 창 진입 <--- 여기서 로딩 속도가 8초대를 찍음.

혹시 나만 이런 문제가 일어남? 코드를 테스트해볼려했는데 이건 처음 보는 문제네.

**Comment by ajh1000** [comment]
와... 일단 원인은 알아냄.

![2](https://user-images.githubusercontent.com/22585023/105735261-d5a3e600-5f76-11eb-8a4d-9ca974142695.PNG)

여기서 자꾸 오랜 시간이 걸린다고 개발자 도구가 알려주길래 뭐가 문제지하고 봤더니.

우리 translate 함수보면 

```
        jsonFile.some(function (item) {
            if (item.kr) {
                if (String(stext).length == String(item.orig).length) {
                    if ((String(stext) == String(item.orig))) {
                        PrintLog(`GET:${String(item.kr)}`);
                        transText = String(item.kr);
```

이렇게 있는데 여기서 String()으로 변수들을 감싼 부분들을 밑에처럼 지우고 돌리니까 번역 속도가 정상으로 돌아옴.

```
 jsonFile.some(function (item) {
            if (item.kr) {
                if (stext.length == item.orig.length) {
                    if (stext == item.orig) {
                        PrintLog(`GET:${item.kr}`);
                        transText = item.kr;
```

크롬 확장 프로그램에서는 이런 이슈 없었는데 탬퍼몽키에서만 이러는거보면 신기하네.

**Comment by sidewinderk** [comment]
혹시 몰라서 한번 더 String 으로 묶어두긴 한 거였는데, 어차피 숫자는 들어와봐야 저 등식을 통과할 일이 없으니 테스트해보고 똑같이 동작한다면 지워도될듯. 하지만 `gbfTrans_test.js`로 한번 PR해서 테스트 한 뒤에 정식 버전을 올려보내는게 좋을듯.

**Comment by ajh1000** [comment]
방금 번역 속도 이슈까지 해결 했음.

이번에도 속도 이슈는 해결까진 아니고 조금은 빨라지도록 했음. 

이게 샤니마스 얘기를 계속 해서 미안한데 그거 번역툴 소스를 보면 후킹을 그런 식으로해야 성능 이슈도 덜할태고 밴으로부터 조금은 더 안전할 것 같다고 생각이듬.

게임 라이브러리에서 사용하는 함수들을 잘 찾아서 후킹을 하는게 좋은데 그 함수를 찾기가 어렵네. 

지금은 적절한 후킹 방법이 안떠올라서 Mutation Observer로 하고있지만 뭔가 좋은 수가 발견된다면 다시 얘기해보는것도 좋을것같음.

암튼, 나머지 이슈들도 처리해서 오늘 저녁 즈음 PR하겠음.

**Comment by sidewinderk** [comment]
사실 좀 더 근본적으로는 샤니마스 한패 같은 느낌으로 설계하는게 맞는데, 
이 번역툴의 시작점이 가능한 구글번역 처럼 소스에 있는 텍스트를 치환하고했던 거 였기 때문에 현재의 형태가 됨.
어지간히 텍스트가 많은 페이지에서도 버그가 있는게 아니면 특별히 성능이슈는 없었으니 이 방법을 고수하고자함.

**Comment by ajh1000** [comment]
맞음 맞음. 나도 동의함. 정말 특별한 일 없으면 이 이슈는 나중으로 미뤄도 될듯.

**Comment by ajh1000** [comment]
다시 속도가 현저히 느려졌을때 열겠음.
