### ISSUE TITLE
번역문 조합기능

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#61]
현재 번역툴에서는 번역문끼리의 조합을 지원하지 않음.
결과적으로 아래와 같은 번역문들:
```
[グラン]がダブルアタック
リリィがダブルアタック
コッコロがトリプルアタック
Lv** ジョヤは麻痺していて動けない！
グラビティが発動！
```
에 대해 아래와 같이 모두 중복으로 번역문을 작성해야함.

```
[그랑]이 더블어택
리리가 더블어택
콧코로가 트리플어택
Lv** 죠야는 마비되어 움직이지 않는다!
그래비티가 발동!
```
하지만 이런 방식으로 번역문을 작성하게되면 들어갈 수 있는 조합수x문장수 만큼의 추가 번역DB 를 작성해야해서 굉장히 비효율적임.

이것을 아래와 같이,
```
[リリィ]がダブルアタック
[コッコロ]がトリプルアタック
[Lv** ジョヤ]は麻痺していて動けない！
[グラビティ]が発動！
```
공통텍스트에 대해서 번역문을 조합하는 기능을 추가하면 좋을 것 같음.

따라서 번역DB에는,
```
がダブルアタック,가 더블어택
がトリプルアタック,가 트리플어택
は麻痺していて動けない！,는 마비되어 움직이지 않는다!
が発動！,가 발동!
```
만 별개로 등록해서 관리하고,

번역툴 번역함수 `translate` 에서는 
1. 이러한 DB, 예를들면 `conjunction`DB에서 먼저 loop를 돌아서
2. 현재 입력받은 원문 중 `conjunction`DB에 등록된 텍스트가 있는지 찾고
3. 만약 입력받은 원문이 `conjunction`DB에 등록된 원문을 포함하지 않는다면 기존과 같은 번역작업을 진행하고 번역문을 반환,
4. 만약 입력받은 원문이 `conjunction`DB에 등록된 원문을 포함한다면 그 부분을 떼어내고 순차적으로 번역작업을 진행하고(이경우 array를 사용해서 loop를 돌리는게 합리적일듯, `conjunction` 단어가 가운데 들어가는 경우도 대응할 수 있도록.)
5. 마지막으로 리스트에서 `conjunction`DB 의 단어를 번역한뒤,
6. 결합하여 반환
```
"リリィがダブルアタック" -> ["リリィ", "がダブルアタック"] // 4번단계#1
["リリィ", "がダブルアタック"]->["리리", "がダブルアタック"] // 4번단계#2
["리리", "がダブルアタック"]->["리리", "가 더블어택"] // 5번단계
["리리", "가 더블어택"]->"리리가 더블어택" // 6번단계
```
하는 방식으로 작성되면 좋을듯함.

혹시 이 기능에 대한 의견이 있을까?

**Comment by ajh1000** [comment]
잠시 다른 일이랑 병행하다가 확인하는게 늦어졌음. 정말 미안함 ㅠ 

이 기능도 알려준 과정대로 하면 가능해보임.

이름 부분은 name.csv에서 찾고, 나머지는 archive.csv 에서 찾아도 될 것 같음.

번역 방식은 그렇게 하면 되는데, 추출은 따로 안건드려도 될려나.

추출은 기존 방식대로 하고 문장을 분리하는 과정은 추출하는 사람 몫으로 남기면 될려나?

**Comment by sidewinderk** [comment]
기존 `archive.csv` 에서 loop를 돌리면 아이템명도 포함되어있기 때문에 오작동할 확률이 높음.
따라서 `conjunction.csv` 를 탐색비용적인 측면에서도 이득이지만, 정확히 필요한 파츠만 빼서 번역을 시도할 수 있기 때문에
다소 DB가 복잡해지는 부작용이 있을지라도 이쪽을 선호하고 싶음.

> 추출은 기존 방식대로 하고 문장을 분리하는 과정은 추출하는 사람 몫으로 남기면 될려나?
그래야 할 듯 함. 사실 이런 류의 번역문은 내가 대부분 작업할 것 같기도하고..

**Comment by ajh1000** [comment]
1번 텍스트 : mcofo*で認証中
--
2번 텍스트 : ***B**D* :参戦ID参加者募集！Lv*** リヴァイアサン・マグナpic.twitter.com/B*DWhmPqsd

전투 화면에서 구원 요청 팝업창 추출한 텍스트임

여기서 트위터 아이디가 추출된 1번 텍스트에서는 트위터 유저도 [플레이어]로 추출되게 할지 고민중.

2번 텍스트는 여기 번역문 조합기능을 활용해서 ```Lv*** リヴァイアサン・マグナ``` 을 처리하면 될것같고,

문제는 뒤에있는 ```pic.twitter.com/B*DWhmPqsd``` 이 부분이네. 이건 추출될때 [트위터URL] 이런식으로 추출하게해야될까?

**Comment by sidewinderk** [comment]
두 텍스트 모두, 

```
で認証中,로 인증중
BD :参戦ID参加者募集！,BD :참전ID참가모집중！
"pic.twitter.com/","pic.twitter.com/"
```
를 conjuction DB에 넣는 것으로 해결할 수 있을 것 같음.

**Comment by ajh1000** [comment]
아 그러네. ㅇㅋㅇㅋ!

**Comment by sidewinderk** [comment]
https://github.com/sidewinderk/gbfTransKor/commit/dd6dc19fff8303c26b47116d776741fecae63bf7

위 Push로 어느정도 기본적인 기능은 구현한 것 같음.

그런데, conjunction db가 archive db 등과는 다르게 처음 크롬을 새로고침 한 상태에서는 로드가 안되고, 반드시 옵션에서 수동으로 DB text 업데이트를 해주거나, 1시간이 지나서 업데이트를 해야지만 작동하는 문제가 있음.
archive DB 업데이트하는 부분과 같이 추가해뒀는데 이상하네.. 혹은 브라우저 캐시 때문일까?

**Comment by sidewinderk** [comment]
일단 잘 동작하는것으로 보이므로 닫아둠
