### ISSUE TITLE
입력받은 원문에 일본어가 포함되어있지 않은 경우 무시하기

### ISSUE THREAD

**Issue by sidewinderk** [sidewinderk/gbfTransKor#62]
현재 번역툴 번역 과정에서 입력받은 원문을 필터링하기보다는 
입력 텍스트가 포함된 Class의 이름으로 필터링하거나 번역을 한뒤에, 거기에 한글이 포함되어있을때만 반환/치환하는 방식을 취하고있음.

이것을 각 translate 함수에서, regex 를 활용하여, 입력받은 원문에 일본어가 포함되어있지 않으면 무시하는 기능을 추가하면 효율적일 것 같음.
이는 단순히 번역툴의 퍼포먼스를 높여줄 뿐만이 아니라 원문을 추출하는 과정에서 번역이 필요하지 않은 아래와 같은 원문들을 원천봉쇄하는 효과를 지닐 것으로 기대함.
```
STATUS,
<span class="num-power*"></span><span class="num-power*"></span><span class="num-power*"></span><span class="num-power*"></span><span class="num-power*"></span>,
<span class="num-power*"></span>,
Job Lv,
```

**Comment by ajh1000** [comment]
굉장히 좋아보임. 이것도 같이 고쳐서 다음 PR떄 하겠음.

여러가지로 테스트해보고 예외사항 생기면 답글 달겠음

**Comment by ajh1000** [comment]
#63 PR에 코드 추가했음. 마이페이지랑 사이드스토리 페이지, 아카룸, 창고 돌아댕겼을땐 문제되보이는건 안보였는데 혹시 문제생기면 말해주삼

**Comment by sidewinderk** [comment]
해결된것 같음. 수고하셨슴.
